### ISSUE TITLE
OrganisationalUnit

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#100]
The substitutionGroup of the OrganizationUnit element defined in the netex_framework\netex_genericFramework\netex_organisation_version.xsd file is DataManagedObject, while it should be OrganizationPart_. 
See fragments from a file: 
<xsd:element name="OrganisationalUnit" abstract="false" substitutionGroup="DataManagedObject">

The OrganizationalUnit comes from the OrganizationPart, but we cannot specify an object of this type in a parts in an Organization due to an incorrect substitution. All other objects from the OrganizationPart can be specified (eg.:  ControlCentre, Department, etc.)
<xsd:element name="Department" abstract="false" substitutionGroup="OrganisationPart_">
<xsd:element name="ControlCentre" substitutionGroup="OrganisationPart_">

**Comment by nick-knowles** [comment]
I have made a fix for this and committed it - I think it has got tagged onto the outstanding pull request
