### ISSUE TITLE
ResponsibilityRole

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#104]
ResponsibilitySet elements can be specified in the ResourceFrame. In the ResponsibilitySet element, you can specify the ResponsibilityRoleAssignment elements that can reference the ResponsibilityRole element. However, I can't find anywhere where I can define ResponsibilityRoles.

**Comment by nick-knowles** [comment]
I have added a fix to add RESPONSIBILITY ROLEs to  to ResourceFrame

**Comment by skinkie** [comment]
Please refer to the pull request #112
