### ISSUE TITLE
Missing Schema constraints for UicOperatingPeriod

### ISSUE THREAD

**Issue by nick-knowles** [NeTEx-CEN/NeTEx#107]
The implementation of  UicOperatingPeriod  (OPerating period, whcih allows a perido to be specified as DayBits . ) is incomplete
 rail ways stule 
(a) There are  no cnstraints for  UicOpreatingPeriodRef
(b) There is no  UicOperatingPeriodRef element
(c) OperatingPeriod  shoudl have  SustitutionGroup   OperatingPeriod_

**Comment by Aurige** [comment]
Already done
