### ISSUE TITLE
Siri_types-v2.0.xsd missing import

### ISSUE THREAD

**Issue by EivindYN** [NeTEx-CEN/NeTEx#120]
I'm trying to parse these files with a parser, but an error occurs because of a missing import file.
Thats because in siri_types-v2.0.xsd there is this line:
<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../xml/xml.xsd"/>
As you can see it tries to search for a folder called xml in the parent folder, but there are none, therefore crashing the parser.
I added this https://www.w3.org/2001/03/xml.xsd to xml/xml and the parser was able to parse the file :)

**Comment by ue71603** [comment]
Thanks!
will be fixed with: https://github.com/NeTEx-CEN/NeTEx/pull/339
