### ISSUE TITLE
Errors in netex_equipmentVehiclePassenger_support.xsd

### ISSUE THREAD

**Issue by syversenkr** [NeTEx-CEN/NeTEx#121]
As discussed with @nick-knowles and @Aurige on Zoom:

Element "WheelchairVehicleRef" has incorrect name (ref. is to WheelchairVehicleEquipment object) and this element plus element VehicleEquipmentRef both have incorrect type (is InstalledEquipmentRefStructure, should be WheelchairVehicleEquipmentRefStructure and VehicleEquipmentRefStructure respectively).

See lines 62, 114 and 119 in:
https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_support.xsd

_See also documentation (xsd:annotation) discrepancies throughout this file, e.g. line 64, 69, 75, 101 and 127._

**Comment by nick-knowles** [comment]
Thanks Krystian - the xml for ActualVehicleEquipment  was actually  wrong and not as shown in the doc

I have made a fix to both the Refs and the and pull request  
See WheelChairEquipmentFix3

**Comment by ue71603** [comment]
I think this is done with new modes and can be closed.
