### ISSUE TITLE
(minor administrative) Outdated XSD file status tags

### ISSUE THREAD

**Issue by syversenkr** [NeTEx-CEN/NeTEx#135]
Should update various `<Status>Version 1.0 Draft for approval</Status>` (or similar) tags throughout the XSD files to correctly reflect their status.

**Comment by ue71603** [comment]
at also the XML spy comments to go away.

**Comment by ue71603** [comment]
covered by: https://github.com/NeTEx-CEN/NeTEx/pull/342 therefore closed now.
