### ISSUE TITLE
Create XML catalog to prevent the requirement for external documents

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#139]
https://en.wikipedia.org/wiki/XML_catalog

Several security related things can be prevented if we ship 'everything'.

**Comment by ue71603** [comment]
Do we add this to the wishlist for 1.3?

**Comment by skinkie** [comment]
Closing this issue because:
1. We don't have any http reference in the entire repository for schemaLocation
2. A catalogue requires explicit loading, which would be a step backwards.
