### ISSUE TITLE
TransportMode in VehicleType

### ISSUE THREAD

**Issue by hennoit** [NeTEx-CEN/NeTEx#155]
There is no possibility to link a _VehicleType_ to a _TransportMode_, although the NeTEx Part 1 documentation already states: "A VEHICLE TYPE shall belong to one TRANSPORT MODE" (par. 7.7.3.1 TRANSPORT MODE - Conceptual model). We also need this link for the Dutch NeTEx Profile.
Probably the Transport**Sub**mode is not needed here, since most values of the xxxSubmode enumerations more concern the kind of service and not the kind of material.
It also does not make sense to allow more than one _TransportMode_.

**Comment by Aurige** [comment]
That's part of the New modes addition
![image](https://user-images.githubusercontent.com/3328999/107631347-1aad6500-6c65-11eb-8ce6-080919fd222a.png)

**Comment by hennoit** [comment]
Great!
