### ISSUE TITLE
add "levelFloorAccess" to (Vehicle)AccessFacilityEnumeration

### ISSUE THREAD

**Issue by hennoit** [NeTEx-CEN/NeTEx#157]
For the Dutch NeTEx Profile we would like to add the value "levelFloorAccess" to the simpleType _VehicleAccessFacilityEnumeration_ (and perhaps analogously to _AccessFacilityEnumeration_).
With this value the user can _explicitly_ see that the vehicle can be entered without any difference in height. Otherwise the best he/she can tentatively conclude is that this is _hopefully_ the case, when there is no mention of "steps", "wheelchairLift", etc.

**Comment by Aurige** [comment]
I'm Ok for this addition. However, we probalby also need a little more since, mainly for trains, is also often linked to the platform/vehicle couple (so for a vehicle it can change from a stop to another, and to a stop it may depend on the vehicle).

**Comment by ue71603** [comment]
@Aurige   @hennoit We have not the AccessLimitation that does this. Is the AccessFacilityEnumeration still needed? 
For AccessFacilityEnumeration lowFloorAccess exists. If not needed, please close. Otherwise confirm and assign to me.

**Comment by ue71603** [comment]
will do

**Comment by Aurige** [comment]
**AssistanceNeededEnumeration** has **LevelAccessIntoVehicle** (from EPIAP), so the need looks covered now
