### ISSUE TITLE
ArrivalTimes in JourneyFrequencyGroup

### ISSUE THREAD

**Issue by hennoit** [NeTEx-CEN/NeTEx#159]
Currently a _JourneyFrequencyGroup_ (like _RhythmicalJourneyGroup_ or _HeadwayJourneyGroup_) contains a _FirstDepartureTime_ and _LastDepartureTime_ to indicate the period in which the _(Template)VehicleJourney_ operates. Both refer to "the time of **departure** from the **first** stop" of the journey.

We are trying to describe flexible (bus)journeys, either running **from** a fixed point (e.g. train station) or **to** a fixed point. In both cases passing times are only certain at that fixed point (probably related to the arrival/departure of trains at the station).
In the case of journeys **from** the fixed point _FirstDepartureTime_ and _LastDepartureTime_ make sense. But in the reverse case of journeys **to** the fixed point one would expect _FirstArrivalTime_ and _LastArrivalTime_, because for these journeys that is the only 'time' available - and most relevant to the passenger wishing to catch a specific train!

Therefore we would like to add _FirstArrivalTime_ and _LastArrivalTime_ to _JourneyFrequencyGroup_, indicating "the time of **arrival** at the **last** stop".
Perhaps it makes sense to use a 'choice' (i.e. Departure OR Arrival).

**Comment by Aurige** [comment]
Hi Henno
Can't you convert to _FirstDepartureTime_ and _LastDepartureTime_ by just substracting the Journey duration to the known _FirstArrivalTime_ and _LastArrivalTime_ ?

**Comment by hennoit** [comment]
Not really, because this are flexible lines and therefore the Journey duration is not known (depends on the reservations). In the timetable we will probably enter a 'maximum' journey duration, but that would lead to unrealistic DepartureTimes. In these cases the only realistic time is the ArrivalTime. Specifying that directly would be much more intuitive for a passenger planning a trip.

**Comment by ue71603** [comment]
fixes: https://github.com/NeTEx-CEN/NeTEx/pull/581
