### ISSUE TITLE
Passenger Assistance Facility Support Values do not align with the XSD

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#160]
![image](https://user-images.githubusercontent.com/502394/113849648-05067880-979a-11eb-9ac9-ea9d4d4a8822.png)

This relates to #53

**Comment by ue71603** [comment]
@skinkie  as this relates to EPIAP. Still work needed?

**Comment by skinkie** [comment]
This relates to it, but also Part1. So it has to align. (and I am still slacking.... because I answer tickets)

**Comment by ue71603** [comment]
Enum or documentation needs to be changed.

**Comment by ue71603** [comment]
really code change needed or only specification document?

**Comment by ue71603** [comment]
only update in specification needed.
Staffing instead of StaffingFacility. 
EmergencyServiceList added.
