### ISSUE TITLE
VersionStatus allowed values do not document value "other"

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#180]
![image](https://user-images.githubusercontent.com/502394/121357101-ca53c480-c931-11eb-99d8-e9d15fe1d63d.png)

Value "other" must me documented.
https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_responsibility/netex_version_support.xsd#L134

Secondary issue from #179

**Comment by ue71603** [comment]
André will add the description also in the xsd.

**Comment by ue71603** [comment]
fixed in #387
