### ISSUE TITLE
EPIP dedicated XSD

### ISSUE THREAD

**Issue by Aurige** [NeTEx-CEN/NeTEx#181]
We now have the EPIP dedicated simplified XSD (https://data4pt.org/NeTEx/GraphicKit/XSD_EPIP.zip) and asssociated examples (https://data4pt.org/NeTEx/GraphicKit/XML_Example_EPIP.zip) but this is not on Github yet. Do you think we shoud add a dedicated folder in the NeTex repo, or create an addition project under NeTEx-CEN ?

**Comment by skinkie** [comment]
Another project. Especially because it is a simplified schema.

**Comment by skinkie** [comment]
Resolved by: https://github.com/NeTEx-CEN/NeTEx-light
