### ISSUE TITLE
Issue in NeTEx Part 3 documentation

### ISSUE THREAD

**Issue by Aurige** [NeTEx-CEN/NeTEx#182]
Copied frm [G Thiesing input in Basecamp
](https://3.basecamp.com/3256016/buckets/2570434/messages/3919361161#__recording_3920044206)

I occasionally recognized a bug in NeTEx Part 3 documentation. In Chapter7.4.1.4.5.3 table 29 there is a mistake in the assignment between 'value' and 'descrition' see below.

![image](https://user-images.githubusercontent.com/3328999/124153707-0099e500-da95-11eb-8a7f-46137a093fef.png)

**Comment by ue71603** [comment]
fixed in sharepoint
