### ISSUE TITLE
Wrong element name "SosPhones" vs. "SosPanel"

### ISSUE THREAD

**Issue by usr1datas1** [NeTEx-CEN/NeTEx#188]
Grop="**PassengerSafetyEquipmentGroup**" contains element="HeightOfSosPanel" that refers to "SosPanel", but element="SosPanel" is missing in this group. I have found "SosPhones" instead. It seems to be wrong, because NeTEx-Model contains "SosPanel" element. 
![SosPanelBug](https://user-images.githubusercontent.com/43411628/124910207-a1375a00-dfeb-11eb-992d-508af1e40239.PNG)

**Proposed solution:**
* remove "SosPhones" element
* add "SosPanel" element

**Comment by skinkie** [comment]
@usr1datas1 out of curiosity which tool do you use to render this?

**Comment by usr1datas1** [comment]
> @usr1datas1 out of curiosity which tool do you use to render this?

Hi Stefan, Dimitri is here.. the Application is "Enterprise Architect", it's not rendered xsd, but separate .ear model

**Comment by Aurige** [comment]
that's right, this is a bug in the XSD it should be SosPanel, and not SosPhone
Is everybody Ok if we correct this now, even if that's not really backward compatible (I don't know already existing usage of this attribut, but I'm aware of some that will come quite soon) ?

**Comment by skinkie** [comment]
If you are sure. Go for it!

**Comment by Aurige** [comment]
I am, but others may not ... waiting a bit for some possible reaction

**Comment by usr1datas1** [comment]
ok for me also
