### ISSUE TITLE
Different classes for RunTimes and WaitTimes

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#19]
When we take a peak at RunTimes/WaitTimes (from TimeDemandType) and RunTimes/WaitTimes (from ServiceJourney) not the same objects are reused. I cannot see why this duplicate exists. Could any of you comment? @nick-knowles @Aurige 

JourneyRunTime vs VehicleJourneyRunTime

**Comment by janosu** [comment]
This is similar to JourneyRuntime and JourneyPatternRuntime. The point of using it is that if you define a JourneyRuntime linked to a TimeDemandType or Timeband on a TimingLink, you can override it for a particular JourneyPattern or VehicleJourney. This is why it is necessary to specify which JourneyPattern applies to JourneyPatternRuntime, and which VehicleJourney to VehicleJourneyRuntime. Of course, in NETEX, the embedded entities already carry this information, but the relationship is represented in the model.

**Comment by skinkie** [comment]
@janosu my question was more in the direction why aren't the element names the same, since the elements represent the same objects, having a different parent. Similar to using for example _Name_ or _Description_. It would be strange to have a _ServiceJourneyName_.

**Comment by ue71603** [comment]
Was this done with the PR?

**Comment by skinkie** [comment]
Not that PR.

**Comment by Aurige** [comment]
from my understanding (see comments in the XSD) the JourneyRunTime is at JOURNEY PATTERN level and VehicleJourneyRunTime is at VEHICLE JOURNEY level (VehicleJourneyRunTime  just adds VehicleJourneyRef or DeadRunRef, and overrides  JourneyRunTime when it exists).

**Comment by skinkie** [comment]
> from my understanding (see comments in the XSD) the JourneyRunTime is at JOURNEY PATTERN level and VehicleJourneyRunTime is at VEHICLE JOURNEY level (VehicleJourneyRunTime just adds VehicleJourneyRef or DeadRunRef, and overrides JourneyRunTime when it exists).

That was not in question :-) My question is why is it not _just_ called RunTime :-)

**Comment by Aurige** [comment]
Names are coming from Transmodel

**Comment by skinkie** [comment]
![image](https://user-images.githubusercontent.com/502394/164180361-b28e602e-4b4f-466f-9f18-31202b62edf6.png)
