### ISSUE TITLE
Documentation request update #187

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#198]
#187 requires update of the documentation.

**Comment by syversenkr** [comment]
See updated [CR-58](https://3.basecamp.com/3256016/buckets/2570434/uploads/4067525886)

**Comment by skinkie** [comment]
The big plan is a sharepoint location hosted at Data4PT, that will allow to incorporate changes by multiple people and have that reviewed as well. Then those can be ticked off here.
