### ISSUE TITLE
AvailabilityConditionRef is not checked for in the XSD

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#2]

**Comment by nick-knowles** [comment]
There is a referential integrity constraint for AvailabilityCondition in the publication schema - are ou sure you have specified a version on the ref? 

		
		<xsd:keyref name="AvailabilityCondition_AnyKeyRef" refer="netex:AvailabilityCondition_AnyVersionedKey">
			<xsd:selector xpath=".//netex:AvailabilityConditionRef"/>
			<xsd:field xpath="@ref"/>
			<xsd:field xpath="@version"/>
		</xsd:keyref>
		<xsd:key name="AvailabilityCondition_AnyVersionedKey">
			<xsd:selector xpath=".//netex:AvailabilityCondition | .//netex:SimpleAvailabilityCondition |  .//netex:ValidDuring "/>
			<xsd:field xpath="@id"/>
			<xsd:field xpath="@version"/>
		</xsd:key>

**Comment by skinkie** [comment]
I see what you mean now, and you are right. If the version is not specified, it will not validate.
