### ISSUE TITLE
PassengerStopAssignment lacks documentation for Order attribute

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#204]
The documentation and examples for PassengerStopAssignment have no reference for the order attribute, but it is required.

**Comment by ue71603** [comment]
Will check with Swiss examples. If yes, then doc update needed.

**Comment by ue71603** [comment]
@skinkie only document update. no update in examples?

**Comment by skinkie** [comment]
Exactly.

**Comment by ue71603** [comment]
@skinkie  what do we express in order?

**Comment by skinkie** [comment]
It is a very good question (other than uniqueness).

**Comment by Aurige** [comment]
I close it here... to be managed together with to https://github.com/NeTEx-CEN/NeTEx/pull/744
