### ISSUE TITLE
Conflicting example for Version elements

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#208]
In the current NeTEx example section the following examples for the Version element have been elaborated. The key takeaway seems to be that the DataSource@version-attribute directly refers to the Version@id-attribute.

![image](https://user-images.githubusercontent.com/502394/127145722-354c22e0-3ffb-4890-9663-beb5158363d8.png)

This is in contrast with the CEN documentation which suggests that the ScheduledStopPoint@version-attribute, refers to the Version@version-attribute.

![image](https://user-images.githubusercontent.com/502394/127145878-3a710069-3fc1-466c-aafb-5685e646b64d.png)

**Comment by Aurige** [comment]
The first example seems to be very specific the the NPTG context and its internal organisation. It's very specific but still valid against the general NeTEx rules for versions.
I don't see a bug here : maybe some additional info & links about NPTG should be provided.

**Comment by ue71603** [comment]
Change any in the example.

**Comment by Aurige** [comment]
see  https://github.com/NeTEx-CEN/NeTEx/pull/471

**Comment by ue71603** [comment]
@Aurige  when all is done in #471 can I close it here?
