### ISSUE TITLE
NewModes: Merging conflicts with master

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#210]
https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/NeTEx_publication.xsd#L2338

Within New-Modes CycleStorageEquipment seems to substite CycleParkingEquipment.

LocalService is complely missing from NeTEx_publication.xsd. This blocks merging #205

**Comment by Aurige** [comment]
Yes, it looks that we have an issue here .... @nick-knowles did we miss something ?

**Comment by Aurige** [comment]
For the LocalService, it is "abstract" so Id constraints are not useful at this level, but  CycleStorageEquipment/CycleParkingEquipment may be a backward compatibility issue
