### ISSUE TITLE
Typo in URL in EPIP profile

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#211]
![image](https://user-images.githubusercontent.com/502394/127295682-f4e4931c-a475-42ef-b1a4-3e453e741b8c.png)

Codespace/XmlnsUrl

**Comment by Aurige** [comment]
Why "needs documentation" ? isn't it just replacing "**ttp**" by "**http**" ?

**Comment by ue71603** [comment]
Problem in the word document.

**Comment by Aurige** [comment]
corrected several times in EPIP
