### ISSUE TITLE
Changes to BookingArrangement

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#216]
I start this issue to collect and then consolidate the BookingArrangement problems I see.

**Multiple booking arrangements**
Already discussed with Nick
BookingArrangements will be changed to bookingArrangements /BookingArrangement, where multiple arrangements are possible.

**BookingURL**
This does not allow for deep links and specififty of ios, android, web. Possibly even substitutions of content are needed. I will work on that a bit and update it here.

**Comment by skinkie** [comment]
Substitution based URLs is something I would really like. I guess we would need to agree on a template format.

**Comment by Aurige** [comment]
See https://github.com/NeTEx-CEN/NeTEx/pull/525

**Comment by ue71603** [comment]
@Aurige  I close it here, as the PR exists. If not ok, pls reopen.
