### ISSUE TITLE
telecabin, cable car or gondola lift

### ISSUE THREAD

**Issue by Aurige** [NeTEx-CEN/NeTEx#218]
In **netex_ifopt_stopPlace_support.xsd** NeTEx defines 2 times "_telecabineplatform_" (for _QuayTypeEnumeration_ and _BoardingPositionTypeEnumeration_)
Matthias raised that the "e" of "telecabine" was a typo, but looking deeper, I looked for "telecabin" in several English dictionnaries and didn't fint it... instead I found "gondola lift" or "cable car" ... is telecabin valid in English ?

**Comment by ue71603** [comment]
https://github.com/NeTEx-CEN/NeTEx/pull/264

**Comment by Aurige** [comment]
The original trailing "e" in _telecabin_ has been solved... may be complement the documentation about what a "lift" can be  ( in NeTEx 'lift' means any type of cableway and also vertical lift)

By the way, looking at it I found new XSD validation issues in master (around ACCESS EQUIPMENT ... I"ll check it later since I have several meetings this morning)

**Comment by ue71603** [comment]
fixed by https://github.com/NeTEx-CEN/NeTEx/pull/580

**Comment by Aurige** [comment]
documentation updated via #580
