### ISSUE TITLE
ScopeOfTicketListOfEnumerations - wrong item type

### ISSUE THREAD

**Issue by usr1datas1** [NeTEx-CEN/NeTEx#235]
Location: https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd

Element: 
<xsd:simpleType name="ScopeOfTicketListOfEnumerations">
    <xsd:annotation>
        <xsd:documentation>List of values for SCOPEs of TICKET.</xsd:documentation>
    </xsd:annotation>
    <xsd:list itemType="**TicketingFacilityEnumeration**"/> --> should be "**ScopeOfTicketEnumeration**"
</xsd:simpleType>

**Comment by Aurige** [comment]
Yes, it definitely needs to be align with the documentation

**Comment by syversenkr** [comment]
Agree on bugfix, see also comments on PR #243

As a sidenote to this issue:
From what I could find in the XSD, none of the defined element "ScopeOfTicket",  "ScopeOfTicketList" or "TicketingFacility" are actually in use. Only the "TicketingFacilityList" / "TicketingFacilityListOfEnumerations" and "ScopeOfTicketListOfEnumerations" are used (the latter, perhaps incorrectly, referenced directly from ScopeOfTicketsAvailable in netex_part_1/part1_ifopt/**netex_ifopt_equipmentTicketing_version.xsd** (line 184)

Furthermore, the _scope_ types differ between the XSD and the spec (part 1), being implemented as ScopeOfTicket(Enumeration) but documented as TicketScope(Enumeration); see 8.4.8.10.3.4.3 TicketScope – Allowed values

On the other hand, perhaps for good measure, the TicketingFacility(Type) is documented twice (in 7.7.14.8.2.4 TicketingFacilityType – Allowed Values and in 8.4.8.10.3.4.1 TicketingFacility – Allowed values)
