### ISSUE TITLE
Inconsistent casing in BaggageTypeEnumeration

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#246]
Within #245 I have noticed inconsistent use of casing.

This may have a high impact.

**Comment by Aurige** [comment]
which casing inconsistency ?

**Comment by skinkie** [comment]
At least pushChair vs wheelchair.

**Comment by Aurige** [comment]
since it's also quite common to find "push chair" in 2 words, this is probably not critical
