### ISSUE TITLE
ComplexFeature not in GeneralFrame

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#258]
@hennoit is using ComplexFeature as a GeneralFrame member, this is not part of the GeneralFrame member list.

Is this an omission?

**Comment by hennoit** [comment]
According to the NeTEx documentation ComplexFeature inherits from SpatialFeature, which inherits from GroupOfPoints, which can be a member of a GeneralFrame.
I think that in the xsd the definition of SpatialFeature is missing a substitutionGroup.
`	<xsd:element name="SpatialFeature" type="GroupOfPoints_VersionStructure" abstract="false">
		<xsd:annotation>
			<xsd:documentation>Abstract SPATIAL FEATURE.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
`

By the way, is it abstract (annotation) or not (attribute)?    :-)

**Comment by Aurige** [comment]
The ComplexFeature  being a DataManagedObject and any DataManagedObject being possibly inserted in a GeneralFrame, it should work anyway ! If it's not possible, there is obviosly a bug somewhere !

![image](https://user-images.githubusercontent.com/3328999/143283509-54e16971-b6b1-4a1a-bbe4-c2d936091693.png)

**Comment by Aurige** [comment]
I just did a try and it looks that there is an issue.... I need to investigate it

**Comment by Aurige** [comment]
Solved by https://github.com/NeTEx-CEN/NeTEx/pull/338
