### ISSUE TITLE
lines not in GeneralFrame

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#259]
@hennoit used "lines" in a GeneralFrame. Is it correct that this element is not available (and that every Line should be individually added?

**Comment by Aurige** [comment]
That's the structure of GeneralFrame: unlike dedicated Frames, they can hold anything (being a dataManagedObject) in any order (so without the _object_**s** grouping mechanism...)

**Comment by skinkie** [comment]
@Aurige thanks. That confirmed my guess.
