### ISSUE TITLE
LiftEquipmentRef within placeEquipments is not allowed

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#260]
Reported in the accessibility meeting.

**Comment by skinkie** [comment]
Might be related to https://github.com/NeTEx-CEN/NeTEx/issues/167

**Comment by Aurige** [comment]
That right it is the same issue as [#167](https://github.com/NeTEx-CEN/NeTEx/issues/260#issuecomment-992505543)

**Comment by ue71603** [comment]
Duplicate of #167
