### ISSUE TITLE
Incorrect naming and cardinality for NeTEx part 3 - 7.6.1.2.3.5 AccessRightParameterValidityParameterGroup

### ISSUE THREAD

**Issue by syversenkr** [NeTEx-CEN/NeTEx#268]
See [PR#267](https://github.com/NeTEx-CEN/NeTEx/pull/267/)

1. Figure 147 — ValidityParameterAssignmentScopeGroup — XSD should be updated to document that the temporalValidityParameters can contain **multipe** TemporalValidityParametersGroup (similar to _validityParameters_)

2. validityParameters is in the table Table 97 – AccessRightParameterValidityParameterGroup **incorrectly** documented as type "LimitingValidityParametersGroup", which should be _Scoping_ValidityParametersGroup

**Comment by nick-knowles** [comment]
UML corrected
![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/79f3c103-b897-4a7f-a234-f12d539e28ab)

**Comment by Aurige** [comment]
Part 3 updated

**Comment by ue71603** [comment]
@Aurige  can we close it?

**Comment by Aurige** [comment]
yes
