### ISSUE TITLE
NAP and EPIP

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#270]
The data that they represent must be available from the master systems. Therefore two new chapters are needed in EPIP:
•	Chapter 10: Master data management for interoperability between data sets. This chapter defines which data needs to be synchronized between operators/countries/systems for lines to be integrated.
•	Chapter 11: Business process blueprints that allow data to be integrated between different NAP.

**Comment by Aurige** [comment]
Do we need to have thin inside EPIP, or can't it be some accompanying documents (white paper, TR, etc.)

**Comment by ue71603** [comment]
Will be dealt here: https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/issues/7
