### ISSUE TITLE
EPIP should disallow suitabilities as EPIAP does not support them

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#271]
EPIP allows for suitabilities. EPIAP does not. Therefore in table 32 of EPIP suitabilites should be marked as not to be used.

**Comment by Aurige** [comment]
agreed on my side

**Comment by ue71603** [comment]
https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/issues/2
