### ISSUE TITLE
EPIP: Extend the use of NOTICES and NOTICEAssignement for accessibility 

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#272]
Extend the use of NOTICES and NOTICE ASSIGNMENT to STOPPLACE and QUAY. A NOTICE may contain additional information to the AccessibilityLimitation, some examples of notices:
•	‘Narrow stop platform, difficult crossing’  (for a quay not wide enough according to the norms for a wheelchair turn)
•	‘The space between platform and tram does not have the same height/width everywhere
•	‘The stop is in a slight bend, so not all doors are accessible’

Affects chapter 7.11 and possibly 8.7, 8.10

**Comment by Aurige** [comment]
You already can do it thanks to the **NoticedObjectRef** in **NoticeAssignment** (that can be a standalone element)... but that's true that this is not explicit and some words about it would help

**Comment by ue71603** [comment]
https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/issues/3

**Comment by ue71603** [comment]
https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/issues/4
