### ISSUE TITLE
How to specify that a bicycle can be brought in the ServiceJourney?

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#282]

**Comment by Aurige** [comment]
You can use the FacilitySet of the associated VehicleType (noCycles/cyclesAllowed/cyclesAllowedInVan/cyclesAllowedInCarriage/cyclesAllowedWithReservation)

**Comment by skinkie** [comment]
So we are missing a VehicleTypeView on ServiceJourney.

**Comment by Aurige** [comment]
We already have the Ref, and  VehicleType  are really objects shared across multiple Journeys .... we can introduce a view, but I definitely prefer the ref here

**Comment by skinkie** [comment]
I cannot express GTFS trips.txt for bicycles allowed.

**Comment by skinkie** [comment]
All relevant, but GTFS only specifies that you can take the bicycle on this "ServiceJourney".

**Comment by ue71603** [comment]
Should a VehicleTypeView be added or not. Stefan thinks that building whole Vehilcetype only from that part, would not be good when importing GTFS.

**Comment by JohanEntur** [comment]
Facilities and type of vehicle does not necessesarily decide wether bringing a bicycle is allowed. You can have the facility but an occation (event, or rush hour) may dictate that it is not allowed. Conversely there might be a low-load line where bringing a bicycle is fine even without special facilities because the bus is largely empty anyway.

**Comment by Aurige** [comment]
From meeting #4 :

- The FacilitySet on the ServiceJourney (in ServiceJourneyPartsGroup) can provide de necessary information (_noCycles/cyclesAllowed/cyclesAllowedInVan/cyclesAllowedInCarriage/cyclesAllowedWithReservation_)
- The FacilitySet can also be used at VehiculeType level
- if ValidityCondition are necessary, the FacilitySet has a ValidityCondition  and multiple FacilitySet can be used allowing different facilities with different ValidityCondition
