### ISSUE TITLE
TypeOfProductCategory in Line

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#30]
Line has a ExternalTypeOfProductCategory, but o TypeOfProductCategory. Is this a bug?

**Comment by nick-knowles** [comment]
The external  reference was added late in the day at the request of the Germans.
Nobody asked for a  native TypeOfProductCategory

**Comment by ue71603** [comment]
In our NeTEx files this is then done by adding a TypeOfProductCategory in the ResourceFrame. Can you live with that @skinkie ? Then we can close this one.

**Comment by skinkie** [comment]
@ue71603 how can that product category be refenced from a line?

**Comment by ue71603** [comment]
In Switzerland it is quite typical. The thing that is defined in V.580 is really a product category and not a sub mode. So it should be put into the line as well. https://www.allianceswisspass.ch/de/www.allianceswisspass.ch/de/asp/Downloadsindex.php?section=downloads&download=20770 

PE Panoramaexpress or  EuroNight or Regionalbahn
Or do you have different understanding of a ProductCategory?

**Comment by Aurige** [comment]
It should be ok via LineClassificationGroup
![image](https://user-images.githubusercontent.com/3328999/163974340-9c847774-9270-4f12-a58f-26acf64dd98f.png)

**Comment by ue71603** [comment]
@skinkie  Can we close it or do we need additional work?

**Comment by skinkie** [comment]
Yep lets close it.
