### ISSUE TITLE
OrganisationValidity-VehicleModes does not align with TransportMode implemented elsewhere in NeTEx

### ISSUE THREAD

**Issue by syversenkr** [NeTEx-CEN/NeTEx#300]
NeTEx part 3 - 7.6.1.2.3.7.1 OrganisationValidity - ParametersGroup and corresponding XML implementations has TransportMode(Enum) implemented as _VehicledModes_ (while still being described as Transport Mode).

This should be aligned with the rest of NeTEx, and VehicleModes _deprecated_. See also PR #145 (pull requested to 'master')

Additionally, the following element is _incorrectly_ named TransportSubmode**l** of type TransportSubmode**l**Enum in the spec. (Is correctly implemented as TransportSubmode in the XSD.)

**Comment by ue71603** [comment]
@Aurige  We did something in PR #145, but the question is:  What else do we need to do.

**Comment by ue71603** [comment]
see also #300

**Comment by Aurige** [comment]
Discussion: to be managed via the alignment with TM MODE update

**Comment by Aurige** [comment]
see https://github.com/NeTEx-CEN/NeTEx/pull/376 + Part 1 documentation update
