### ISSUE TITLE
EuroClass in VehicleTypeTotalCapacityGroup

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#304]
Why is there an EuroClass in a VehicleTypeTotalCapacityGroup?

https://github.com/NeTEx-CEN/NeTEx/blob/new-modes/xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd#L289

**Comment by Aurige** [comment]
yes, it looks that it has to be moved in **TransportTypePropertiesGroup** (just above in **TransportTypeGroup**)

**Comment by skinkie** [comment]
It has been part of VehicleTypePropertiesGroup before.

**Comment by skinkie** [comment]
@Aurige what is your preference?

**Comment by Aurige** [comment]
**TransportTypeGroup** (thogether with **PropulsionType**, **FuelType**, etc.) looks to be a better place to me, alnd aslo closest in the element hierarchy

**Comment by skinkie** [comment]
If everyone is happy :-)

**Comment by ue71603** [comment]
happy..

**Comment by Aurige** [comment]
Happy !

**Comment by skinkie** [comment]
@Aurige first honest reply ;-)
