### ISSUE TITLE
VehicleMode

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#311]
@hennoit I'll remove this from "next". Can you please check where you want to have VehicleMode in the current "new-modes" master.

https://github.com/NeTEx-CEN/NeTEx/commit/9d60fe683794e375a383a2c6ca7542470975c663

**Comment by hennoit** [comment]
In the new-modes xsd VehicleType already contains TransportMode, so there is no need (anymore) to add VehicleMode.
