### ISSUE TITLE
TimingPoint missing PrivateCode

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#32]
Could someone validate that TimingPoint at this moment is missing PrivateCode?

**Comment by ue71603** [comment]
I can't see a PrivateCode. There is PointNumber, however. Which might be used for this. But in this file also TiminLink
Strangly LinkSequence then has a PrivateCode. Also ServiePattern. To me it also seems a bit arbitrary, but I didn't miss it up until now.
@Aurige  @duexw : Do you think we must work on PrivateCode in more detail or not?

**Comment by skinkie** [comment]
I think the private code should be moved up. This required a breaking schema change.

**Comment by Aurige** [comment]
I don't miss it on my side (and never got request for it). 
If moving up PrivateCode may look nice, it's big schema change and will break compatibility for all users of already existing PrivateCode

**Comment by skinkie** [comment]
> I don't miss it on my side (and never got request for it). If moving up PrivateCode may look nice, it's big schema change and will break compatibility for all users of already existing PrivateCode

@Hennoit requested it. TimingPoints are in the Dutch used in the AVL system.
