### ISSUE TITLE
SeriesConstraint

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#33]
Hi,

In the SeriesConstraint_VersionStructure type the journeyPatterns, prices and replaces is 0..*, but I think they should be 0..1.

**Comment by skinkie** [comment]
Why exactly?

**Comment by janosu** [comment]
Hi,

Let see for example journeyPatterns member. The journeyPatterns member type is SeriesConstraintPrices_RelStructure, which is contains 1..* JourneyPatternRef element. If you define the journeyPatterns as 0..*, this mean List of SeriesConstraintPrices_RelStructure.

p.s.
In all classes where OneToMany relationship is defined in members, the relationship member is 0..1, because the relationship member contains the list of entity or entity reference.

**Comment by janosu** [comment]
I checked the latest version and the error still exists. In SeriesConstraint, you should remove "maxOccurs = unbounded" from journeyPatterns, prices, replaces and farePointsInPattern members in the xsd file.

**Comment by janosu** [comment]
I checked the latest version the error still exists. Please have someone look at the SeriesConstraint_VersionStructure type in the netex_part_3/part3_fares/netex_fareSeries_version.xsd file. The problem is the cardinality of elements of type xxx_RelStructure.

**Comment by nick-knowles** [comment]
This shoulc be okay as it is within an unbounded choice in with an unbounded  . See

 (https://user-images.githubusercontent.com/1826507/85236208-ce7e8d80-b413-11ea-834d-63e91dd4998f.png)

I just tried validating the following at it was fine 
   <seriesConstraints>
	 <SeriesConstraint id="tap:Lille+Valenciennes" order="1" version="1.0">													 
		<Itinerary>Lille * Valenciennes</Itinerary>													 
             <SeriesType>stationToStation</SeriesType>											 
	      <prices>
   	         <SeriesConstraintPriceRef versionRef="a" ref="Price1"/>
	            <SeriesConstraintPriceRef versionRef="a"  ref="Price2"/>
		 </prices>
	   </SeriesConstraint>
    </seriesConstraints>

**Comment by janosu** [comment]
Hi Nicolas,
Thanks your reply. 
I do not understand, why the outer element cardinality is unbounded? 
Based on the linked image, the "prices" can be repeated several times, while the content can already be a set of references or objects. 
Based on the above, you can produce such a fill:
<prices>
	<SeriesConstraintPriceRef ref="..." />
	<SeriesConstraintPriceRef ref="..." />
</prices>
<prices>
	<SeriesConstraintPriceRef ref="..." />
	<SeriesConstraintPriceRef ref="..." />
</prices>

I think the cardinality of "prices" should be 0..1, instead of 0..unbounded.
But if not, how do we group references or objects into several parts? There is no information on this in either the model or the documentation. This is why I say that in this case there will be a typo, because in all other entities the relationship type data members have 0..1 cardinality.

**Comment by ue71603** [comment]
@Aurige  Pri ces are not so my thing. Can you tell, if we should change it?

**Comment by nick-knowles** [comment]
I agree this is a bug, Fix made.

**Comment by ue71603** [comment]
fixed in PR https://github.com/NeTEx-CEN/NeTEx/pull/573
