### ISSUE TITLE
examples/standards

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#332]
Hi Christophe
Should all examples in standards also validate with NeTEx? If yes, then I have to include them in travis as well.
Kind regards
M

**Comment by Aurige** [comment]
yes they should

**Comment by ue71603** [comment]
Most done by now. However:
* nta needs a lot of fixing and
* norway is completly broken.
There are also some subfolders I need to integrate or delete.

@skinkie  @Aurige : Who will fix nta and norway examples?

Other questions about standards sub folder: 
* Why are there no VDV462 examples?
* tfl contains only a pdf. What for?
* neptune: the ligne7 zip contains a xml, but it is broken. Is it needed there?

* The folder ws_siri_request is not included in travis: should it be

**Comment by ue71603** [comment]
What shall I do? It does not work with travis => I can't include it in travis. If you think it is ok that way and I should just not add it to travis, then we are done.

**Comment by ue71603** [comment]
(with the norway example).

**Comment by skinkie** [comment]
Don't include it in Travis yet.

**Comment by ue71603** [comment]
we worked on that. I think it is ok as it is with the relevant PR
