### ISSUE TITLE
Assigned vehicle for ServiceJourney

### ISSUE THREAD

**Issue by codeape2** [NeTEx-CEN/NeTEx#345]
Context/background:
- Example: Route planning for car ferry Molde-Vestnes assigns the vessel "MF Malmefjord" to the service journey at 02:30 Monday-Friday.
- This information is potentially useful for the passengers. For instance trucks carrying dangerous goods can phone "MF Malmefjord" ahead and enquire re. available spots. Also useful for ambulances, fire trucks etc.
- Currently this information is only available in the PDF timetables on the ferry company website (see screenshot, the letters A-D refer to the ferries listed with contact phone number top right).
![image](https://user-images.githubusercontent.com/97742/165110346-c2085727-6b5c-4cfa-a0bf-dad68c8154ad.png)

- In Norway, some authorities use NoticeAssignment/Notice to convey this information in NeTEx

Questions/issues:
- What is the best way to include this information in NeTEx? I.e. for each ServiceJourney, refer to which ferry is assigned.
- The vessel/vehicle information should include: name, identifier (ships: IMO/MMSI) and contact information
- In the xsd I find Vehicle, VehicleRef, vehiclesInFrame_RelStructure etc. but I can not see any way to express the connection between a ServiceJourney and a Vehicle.

**Comment by JohanEntur** [comment]
@syversenkr

**Comment by JohanEntur** [comment]
We've received the first dataset with such data.

`					<vehicles>
						<Vehicle id="HAV:Vehicle:1" version="1">
							<Name>MS Havila Capella</Name>
							<OperationalNumber>9865570</OperationalNumber>
							<OperatorRef ref="HAV:Operator:999523587" version="1"/>
							<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
						</Vehicle>
						<Vehicle id="HAV:Vehicle:2" version="1">
							<Name>MS Havila Castor</Name>
							<OperationalNumber>9865582</OperationalNumber>
							<OperatorRef ref="HAV:Operator:999523587" version="1"/>
							<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
						</Vehicle>
						<Vehicle id="HAV:Vehicle:3" version="1">
							<Name>MS Havila Polaris</Name>
							<OperationalNumber>9873759</OperationalNumber>
							<OperatorRef ref="HAV:Operator:999523587" version="1"/>
							<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
						</Vehicle>
						<Vehicle id="HAV:Vehicle:4" version="1">
							<Name>MS Havila Pollux</Name>
							<OperationalNumber>9873761</OperationalNumber>
							<OperatorRef ref="HAV:Operator:999523587" version="1"/>
							<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
						</Vehicle>
					</vehicles>
				</ResourceFrame>
				<InfrastructureFrame id="HAV:InfrastructureFrame:1" version="1">
					<vehicleTypes>
						<VehicleType created="2022-09-21T11:41:00.900" id="HAV:VehicleType:1" version="1">
							<Name>Model</Name>
							<Description>Hybrid cruise vessel</Description>
							<SelfPropelled>true</SelfPropelled>
							<EuroClass>DNVGL</EuroClass>
							<PassengerCapacity>
								<TotalCapacity>640</TotalCapacity>
							</PassengerCapacity>
							<LowFloor>true</LowFloor>
							<HasLiftOrRamp>true</HasLiftOrRamp>
							<Length>124</Length>
							<Width>22</Width>
						</VehicleType>
					</vehicleTypes>
				</InfrastructureFrame>`

**Comment by JohanEntur** [comment]
https://github.com/NeTEx-CEN/NeTEx/issues/401 Is required to add the contact information to each "vehicle" (ship).

**Comment by ue71603** [comment]
See #584  . I added the ContactDetails there.  also did the work asked for here. Will be discussed. Not sure, if it will be used in the end. I think that going through VehicleType is more relevant in classical public transport. For ferries and alternative modes. I think the VehicleType is not a direct concept, but   it is  ServiceJourney - Vehicle - VehicleType. But I guess @Aurige  has an opinion on that....
