### ISSUE TITLE
PublicCode for TariffZone/FareZone

### ISSUE THREAD

**Issue by syversenkr** [NeTEx-CEN/NeTEx#367]
There is a request to enable the optional exchange of a PublicCode in TariffZone/FareZone data, as some data providers may have (full) Name, (abbreviated) ShortName, (textual) Description and a PublicCode (in addition to an internal, most often system related, PrivateCode) for such zones.

Ok adding the PublicCode element to e.g. the ZoneGroup or TariffZoneGroup (both groups are defined in netex_zone_version.xml and included in both TariffZone as well as FareZone data types) ?
Or any good reason _not_ to ?

**Comment by JohanEntur** [comment]
Hi,

It would be good if we were able to get this included in the NeTEX XSD as soon as possible. We currently have active datasets with publicCodes for fare zones. How should we proceed?

**Comment by Aurige** [comment]
So you can add a pull request to "next" branch
