### ISSUE TITLE
TaxiServiceGroup is empty

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#377]
Why is TaxiServiceGroup an empty group?
xsd\netex_part_5\part5_rc\netex_nm_mobilityService_version.xsd
It seems to me that some attributes are misggin for a TaxiService: E.g. the defining area. (area of operation). This would be a thing like a FlexibleLine. But I don't see, how I could add it.
Or should I look at a different place?

Am I right that there is not much between the TaxiService and the SingleJourney? These are the main elements for a taxi "trip"
For your information @davidr1234

**Comment by Aurige** [comment]
TaxiServiceGroup is just a placeholder for now, be we didn't get requirements that are not yet fulfilled by previously inherited attribute.
That's right for area... probably to be managed as a geo fence (mobilityServiceConstraintZones)
