### ISSUE TITLE
VehicleScheduleFrame: order for Block/TrainBlock

### ISSUE THREAD

**Issue by syversenkr** [NeTEx-CEN/NeTEx#386]
Perhaps more of a discussion point than an _issue_, but similar to _necessary_ order attribute for Via (ref. #378) it would be helpful for data management having an explicit way of assigning order to the elements in a `blocks` list. Preferably through an **order** _attribute_ on each Block/TrainBlock.

Which would be equivalent to the already available **order** attribute for its underlying `blockParts` i.e. on the BlockPart/TrainBlockPart element. (The order attribute is similarly available on Journey - `parts` - JourneyPart)

**Comment by Aurige** [comment]
The VehicleJourneys building up a block are in sequence in the **BlockComponentsGroup.journeys** and are expected to be properly ordered in that sequence: isn't it enough ?

**Comment by ue71603** [comment]
@syversenkr  I close this issue with the comment from @Aurige . When not ok, pls reopen and leave a comment.
