### ISSUE TITLE
ServiceExclusion with Collection LineRefs

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#391]
At this point there are two RoutingConstraint options:

1. ServiceExclusion; having a reference to a service journey pattern, a from scheduled stop point and a to scheduled stop point.
2. RoutingConstraintZone; having a reference to points, and a line.

If one wants to specify the direction on which the routing constraint applies, only a ServiceExclusion is possible.
If one wants to reference a line, instead of a journey pattern, only a RoutingConstraintZone is possible.

I would like to request to add lines (and possibly groupoflines) to ServiceExclusion.

**Comment by Aurige** [comment]
Ok, I added it to the list for the revision

**Comment by ue71603** [comment]
Is it somewhere else or should it be done?

**Comment by nick-knowles** [comment]
It woudl also be possible to a have link  from a RoutingConstraintZone to  AllowedLineDirection using a LineInDirectionRef which specifies a DIRECTION as well as a LINE. This allow meaning ful names to be used eg eastbound, westbound  etc

But here is the UML for adding LINE to SERVICE EXCLUSION

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/5d3cafe8-3348-4b5e-939d-b770018143b0)
e

**Comment by Aurige** [comment]
Discussion: accepted with @nick-knowles 's proposal + Allowed line direction => PR to be done (@nick-knowles  )

**Comment by ue71603** [comment]
addressed in  #608
