### ISSUE TITLE
Predicted occupation

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#398]
In The Netherlands we exchange predicted occupation for journeys three days forward. This might be something from the perspective of NeTEx or SIRI-PT.

**Comment by ue71603** [comment]
@skinkie  you want this in NeTEx? Or do we keep it in SIRI?

**Comment by skinkie** [comment]
I can live with SIRI-PT, but I don't know if it is already in...

**Comment by BredeD** [comment]
We want this in NeTEx and ET. PT is, in our perspective, deprecated and replaced by NeTEx.

**Comment by Aurige** [comment]
Discussion: to be added in NeTEx: for Journey/JourneyPart/DeckPlan. Make explicit that it is Expected (predicted, not realtime). Try to reuse SIRI's structure
PR to be drafted (who @Aurige @ue71603 )

**Comment by ue71603** [comment]
addressed by #605
