### ISSUE TITLE
VehicleRef on ServiceJourney

### ISSUE THREAD

**Issue by JohanEntur** [NeTEx-CEN/NeTEx#400]
It seems it is currently not possible to add a `VehicleRef` to a ServiceJourney. It may be possible through some TrainElement wizardry, but my usecase is a ship so using TrainElement is going to be quite strange. 

Today only VehicleTypeRef is allowed on ServiceJourney. This will not suffice since I need to reference specific vehicles. Below is the information I have about the vehicles. Each vehicle (ship) has an individual name and the goal here is to be able to present ship name and capacity to the end users.

I presume this has some implication for several elements but this is the basic need for my specific usecase.

```	<vehicles>
		<Vehicle id="HAV:Vehicle:1" version="1">
			<Name>MS Havila Capella</Name>
			<OperationalNumber>9865570</OperationalNumber>
			<OperatorRef ref="HAV:Operator:999523587" version="1"/>
			<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
		</Vehicle>
		<Vehicle id="HAV:Vehicle:2" version="1">
			<Name>MS Havila Castor</Name>
			<OperationalNumber>9865582</OperationalNumber>
			<OperatorRef ref="HAV:Operator:999523587" version="1"/>
			<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
		</Vehicle>
		<Vehicle id="HAV:Vehicle:3" version="1">
			<Name>MS Havila Polaris</Name>
			<OperationalNumber>9873759</OperationalNumber>
			<OperatorRef ref="HAV:Operator:999523587" version="1"/>
			<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
		</Vehicle>
		<Vehicle id="HAV:Vehicle:4" version="1">
			<Name>MS Havila Pollux</Name>
			<OperationalNumber>9873761</OperationalNumber>
			<OperatorRef ref="HAV:Operator:999523587" version="1"/>
			<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
		</Vehicle>
	</vehicles>
</ResourceFrame>
<InfrastructureFrame id="HAV:InfrastructureFrame:1" version="1">
	<vehicleTypes>
		<VehicleType created="2022-09-21T11:41:00.900" id="HAV:VehicleType:1" version="1">
			<Name>Model</Name>
			<Description>Hybrid cruise vessel</Description>
			<SelfPropelled>true</SelfPropelled>
			<EuroClass>DNVGL</EuroClass>
			<PassengerCapacity>
				<TotalCapacity>640</TotalCapacity>
			</PassengerCapacity>
			<LowFloor>true</LowFloor>
			<HasLiftOrRamp>true</HasLiftOrRamp>
			<Length>124</Length>
			<Width>22</Width>
		</VehicleType>
	</vehicleTypes>
</InfrastructureFrame>
```

This usecase is closely tied to this issue: https://github.com/NeTEx-CEN/NeTEx/issues/345

**Comment by JohanEntur** [comment]
I've also understood from a colleague that you can link Vehicles to ServiceJourneys per date. This may solve the issue in some situations. Perhaps DatedServiceJourney is the best solution? Happy to hear suggestions. Likely there isn't one solution that works perfectly for all usecases.

**Comment by ue71603** [comment]
Fixer here: https://github.com/NeTEx-CEN/NeTEx/pull/584
