### ISSUE TITLE
CustomerServiceContactDetails on Vehicle

### ISSUE THREAD

**Issue by JohanEntur** [NeTEx-CEN/NeTEx#401]
This is a companion issue to https://github.com/NeTEx-CEN/NeTEx/issues/400

The usecase is that many ferry/boat/ship Lines use specific ships. Sometimes the customer is instructed to make direct contact with the staff onboard the vessel. This contact information is therefore directly tied to a specific vehicle, not a customer information centre.

Therefor I request that CustomerServiceContactDetails is extended to Vehicle.

Example:
```
<Vehicle id="HAV:Vehicle:4" version="1">
	<Name>MS Havila Pollux</Name>
	<OperationalNumber>9873761</OperationalNumber>
	<OperatorRef ref="HAV:Operator:999523587" version="1"/>
	<VehicleTypeRef ref="HAV:VehicleType:1" version="1"/>
	<CustomerServiceContactDetails>
		<Email>pollux@havila.no</Email>
		<Phone>+47 900 00 00</Phone>
		<Url>https://www.havila.no/pollux</Url>
	</CustomerServiceContactDetails>
</Vehicle>
```

**Comment by ue71603** [comment]
fixed in #584
