### ISSUE TITLE
Missing enum in TrainElementTypeEnumeration  truckTransporter

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#433]
The enum is missing a transporter for heavy vehicles.
	<xsd:simpleType name="TrainElementTypeEnumeration">
		<xsd:annotation>
			<xsd:documentation>Allowed values for TYPE OF TRAIIN ELEMENT.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="buffetCar"/>
			<xsd:enumeration value="carriage"/>
			<xsd:enumeration value="engine"/>
			<xsd:enumeration value="carTransporter"/>
			<xsd:enumeration value="sleeperCarriage"/>
			<xsd:enumeration value="luggageVan"/>

...and probably also in 	RailSubmodeEnumeration		<xsd:enumeration value="truckTransportRailService">

and we have the case that multiple Submodes might exist.

**Comment by Aurige** [comment]
Ok, I add it for discussion with the group

**Comment by nick-knowles** [comment]
would have been better if we had called carTransporter vehicleTransporter instead

Could add enum value of  largeVehicleTransporter ?

**Comment by ue71603** [comment]
PR done
