### ISSUE TITLE
Prerequisites to usage of a line: you need to be in a car (e.g.)

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#434]
Matthias:
We currently study NeTEx / SIRI/ OJP for car transport (on trains and ships)
 
Questions:
1.	How do we model this on a Line/VehicleJourney? With Mode/Submode it is not necessarily clear, that there are preconditions to transport. E.g. one needs a bicycle, bike, car or truck to get transported.
2.	Same applies to SIRI.
3.	For car transport one usually needs to be with a car (sometimes bike and sometimes even bicycle). How should we model this in the OJP request? Wit ItModeToCover and then it finds it? We also would need an ItModeToCover in OJPStopEventRequest and we need that information also in the response. Was something like that already considered?
 

Christophe:
There is a carTransportRailService submode ... and also a carTransporter TrainElementType. But I don't think that we really have an explicit "precondition".
Trucks are for freight, so not really in the scope of NeTEx
Bike in train is a facility or a BikeRack Equipement.

Matthias:

I don’t think this is what this is about.

We have a carTransportRailService between Kandersteg and Goppenstein. You can use it:
•	When you are driving a car
•	When you are driving a bike
•	When you are driving a bicycle
•	Trucks can only be loaded on trains with a special attribute (high-profile)
•	If you show up without a mentioned vehicle, then you can’t use it.

The green marked ones are sometimes not available for other carTransportRailServices in Switzerland.

For touristic transport sometimes you need skis, snowboard or a bicycle to use it.

So I guess we should define something in Transmodel and NeTEx that 

<PrerequisiteEquipmentOrVehicleList>car bike bicycle</PrerequisiteEquipmentOrVehicleList>
Or
<PrerequisiteEquipmentOrVehicleList>ski snowboard</PrerequisiteEquipmentOrVehicleList>
In the LinePropertiesGroup.

**Comment by ue71603** [comment]
I think this is fixed with #600 as well. Not as a list, but almost similar. I guess if  @Aurige, if you prefer a List pls tell in #600

**Comment by Aurige** [comment]
Doc updated based on https://github.com/NeTEx-CEN/NeTEx/pull/600
