### ISSUE TITLE
JourneyPart and LineRef/TypeOfProductCategory

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#435]
JourneyPart allows for changes of most elements of VehicleJourney. Line and TypeOfProductCategory are not included.

In the modeling of many trains, this is what happens.

An interregional train becomes a suburban train on the last few stations sometimes.

Naturally this can be modeled as two VehicleJourneys and an Interchange with StaySeated. However, then we wouldn't need JourneyPart at all and could do everything that way.

So I think it should be considered that a JourneyPart can do all things that a VehicleJourney can do.

**Comment by Aurige** [comment]
I think that we can add ProductCategory tou JourneyParts ... 
but you are also mentioning the Line: that would really break the structure and that would really be weird in the communication to passenger. To change Line then the split in 2 VehicleJourneys and an Interchange with StaySeated make sense in my opinion.

**Comment by ue71603** [comment]
I know this is the Transmodel/NeTEx way for the LINE. 
The take from some people at SBB is, that the LINE definition is too much emphasising local public transport.  In the long distance world it is I go Bern to Zürich  (which is not a LINE in any sense).

So the feeling seems persistent in some parts, that Transmodel is model the reality of long-distance travel. 

Otherwise we should remove JourneyPart completly and always tell to do ServiceJourneys and Interchanges.

**Comment by Aurige** [comment]
Long discussion here ... I don't really agree: rail operator have a tendency to focus on their operational organisation, and sometime forget the passenger point of view. Typically, I don't know the details for  Bern to Zürich, but if you take the Paris - Nice one, what about all intermediate stops (they are not anymore managed as O/D), also what about the fact that some journey are direct and other have intermediate stops, and even that a connection is sometime mandatory. The LINE is what is expected to be advertised, and not a specific O/D

**Comment by Aurige** [comment]
Solved by https://github.com/NeTEx-CEN/NeTEx/pull/527

**Comment by skinkie** [comment]
@Aurige don't close until merged. And automatically close by "Fix #"
