### ISSUE TITLE
Ambiguous definition of GroupTicket and its size limits

### ISSUE THREAD

**Issue by futu-waino** [NeTEx-CEN/NeTEx#446]
Hi,

the definitions of GroupTicket and its allowed number of companions are
ambiguous. They can be interpreted differently depending on how literally you
read them. It's not clear, whether the original ticket holder is included or
excluded in the number of persons permitted.

For GroupTickets, the specification says following [1]:

> The number and characteristics of persons entitled to travel in addition to
> the holder of an access right.

Emphasis on "in addition to".

For GroupTicketSizeGroup, the specification of MaximumNumberOfPersons says
following [2]:

> Maximum number of persons overall allowed on GROUP TICKET.

The GroupTicketSizeGroup also contains the CompanionProfiles, documented as
follows [3]:

> Minimum and maximum numbers of users in each category  allowed on GROUP TICKET.

In our opinion, the wording of the GroupTicket / GroupTicketSizeGroup are
ambiguous. It's unclear, whether the GroupTicketSizeGroup parameters include or
exclude the one person holding the base ticket.

Because the definition of GroupTicket says it grants travel rights "in addition
to the holder of an access right", we can think of it as an extension to the
regular ticket. One could interpret, that the GroupTicketSizeGroup only limits
the additional companions traveling. In other words, it's not counting the
person holding the base ticket.

This interpretation is compounded by the fact, that the CompanionProfiles list
their own specific limits. Although the descriptions for the limits in the
GroupTicketSizeGroup talk about "the Group Ticket overall", we could think of
them to mean the contents of the GroupTicket object (and only the GroupTicket),
consisting of a minimum/maximum sum of all the companion profiles, but excluding
the base ticket holder.

All of the examples we've found seem to use the GroupTicketSizeGroup limits as
the total minimum/maximum number of persons traveling, which includes the base
ticket holder.

Can you clarify the definitions?

[1] https://github.com/NeTEx-CEN/NeTEx/blob/12848763e6a9340b703de048368f2dd518ac3e27/xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd#L266
[2] https://github.com/NeTEx-CEN/NeTEx/blob/12848763e6a9340b703de048368f2dd518ac3e27/xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd#L328
[3] https://github.com/NeTEx-CEN/NeTEx/blob/12848763e6a9340b703de048368f2dd518ac3e27/xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd#L338

**Comment by ue71603** [comment]
Addressed in: https://github.com/NeTEx-CEN/NeTEx/pull/589

@futu-waino  I hope this does the trick for you.

**Comment by futu-waino** [comment]
Now it's clear. Thanks!
