### ISSUE TITLE
EPIP example wrong

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#455]
We currently have an EPIP example in our repository that in my opinion has the wrong semantics going on for the version attribute.

https://github.com/NeTEx-CEN/NeTEx/blob/master/examples/standards/epip/epip_common_profile.xml#L49

Everything in that file refers to:
```
version="epip:1.0"
```

But reviewing the actual Version-element, it uses version="any" while version="epip:1.0" would be (in my opinion) the correct way.
```
						<Version id="epip:1.0" version="any">
							<Description>EPIP version 1.0</Description>
							<VersionType>baseline</VersionType>
						</Version>
```
Hence:
```
						<Version id="epip:1.0" version="epip:1.0">
							<Description>EPIP version 1.0</Description>
							<VersionType>baseline</VersionType>
						</Version>
```

What we are currently missing in our XSD is the check if a version actually exists.

Which then causes a major incompatibility with EPIP which explicitly state:

"In EPIP the Version element itself not populated; a simple version number in the version attribute of an EPIP element is used to indicate the version."

I think this deserves a change request, adding the Version element is _trivial_, especially if there is a single version anyways.

**Comment by Aurige** [comment]
right, there is an issue here: the `<version ...>` is against the mention you are pointing and furthermore, looking deeper it looks that this version in the example is the version of the EPIP profile, and is use later on as a version of Data or Data set which is inconsistent.
And in any case, if the version is provided, I would expect something like `<Version id="epip" version="1.0">`
So I agree that this is a bug to correct

**Comment by skinkie** [comment]
In that case I would expect version="1.0" on every element.

**Comment by Aurige** [comment]
except if your providing system has no version management at all (which is often the case as explained in the same EPIP chapter), in that case no version is Ok (or "any" when you want/need to trig the constraint control)

**Comment by skinkie** [comment]
Not ok for me, then it should provide a fixed value too.

**Comment by ue71603** [comment]
@skinkie  only documentation to do? something else? we tighened the id requirement already.

**Comment by skinkie** [comment]
Version-element deprecated. Can be closed. Only documentation to do.

**Comment by Aurige** [comment]
Part 1 documentation was updated. No need in EPIP Document
