### ISSUE TITLE
DocumentModificationDetailsGroup

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#456]
Since DocumentModificationDetailsGroup explicitly mentions a fileName, I wondered where it was used. It is not used in the current schema. What was the target element it should have been used on?

**Comment by ue71603** [comment]
The only valid element would be PublicationDelivery in my view.

**Comment by ue71603** [comment]
However, knowing the filename already then might be a bit early.

**Comment by skinkie** [comment]
Personally, I would like to have the ability to announce things on the frame's _prerequisites_. Hence, 'load this file, if you want to have this additional content'.

**Comment by Aurige** [comment]
Looks like an old dead branch ... without any obvious usage for it I would just remove it at that point

**Comment by ue71603** [comment]
@Aurige  @skinkie  should I just remove the attribute?

**Comment by skinkie** [comment]
Maybe also run a query for other unreferenced groups.

**Comment by Aurige** [comment]
discussed ...

**Comment by ue71603** [comment]
Rest will be dealt in the Prerequisites issue
