### ISSUE TITLE
RouteInstruction seem to be duplicated

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#466]
https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_part_1/part1_networkDescription/netex_routeInstruction_version.xsd#L76

**Comment by ue71603** [comment]
I guess the xs:documentation was not adapted. Or do you see a different problem?

**Comment by skinkie** [comment]
The RouteInstruction Element is duplicate twice right?

**Comment by Aurige** [comment]
Right the first one should be a ref 
`<xsd:element ref="RouteInstruction" maxOccurs="unbounded"/>`

**Comment by ue71603** [comment]
fixed in #588 588
