### ISSUE TITLE
Integrate LineEquipment air conditioning

### ISSUE THREAD

**Issue by lg3175** [NeTEx-CEN/NeTEx#480]
We would like to integrate the line equipment data on the netex. 
It seems that the Netex profile for networks is appropriate, however only the notion of accessibility equipment is available. If we wish to integrate a data for example the presence of air conditioning on board a line (True or False) how can we integrate it into this netex profile?

**Comment by lg3175** [comment]
I agree with you, VehicleType is the thinnest level for this information. However, operator haven't this information at the line level, they say if all vehicles have air-conditioning equal True if one of them vehicle doesn't equal false.
The vehicle level can't permit to push if, for example, Line A is air-conditioning or not in the application.

**Comment by skinkie** [comment]
No, Vehicle is the finest level.

**Comment by Aurige** [comment]
I would be in favour of having an AC facility
There is already this information in VehicleModel (via  VehicleModelProfile/CarModelProfile) and in WaitingEquipment... but that is not covering all the needs for me.

**Comment by nick-knowles** [comment]
There is currently an air conditioning  boolean

	• On WaitingEquipment for  Stops and bus shelters
	• On DeckSpace (new)   for onboard 
	• On car model profile for perosnal drive vehicles

Should probably be a more detailed **EnvironmentControlFacility** attached to SERVICE FACILITY SET / ACCOMMODATION with  a list of values e.g. 
    airConditioning / heating / noConditioning/ noHeating /  windowsCanBeOpened / sealedWindows

And maybe a separate a LightingControlFacility also e.g. 
tintedWindows / blinds / curtains  / dimmableLights / lightsAlwaysOn / noNaturalLighting

**Comment by ue71603** [comment]
addressed in #601

**Comment by Aurige** [comment]
Doc updated in https://github.com/NeTEx-CEN/NeTEx/pull/601
