### ISSUE TITLE
duplicate vehicleJourneyStopAssignmentsInFrame_RelStructure and VehicleJourneyStopAssignmentsInFrame_RelStructure

### ISSUE THREAD

**Issue by HPOkurDB** [NeTEx-CEN/NeTEx#489]
In the XSD netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd there are the two complexTypes vehicleJourneyStopAssignmentsInFrame_RelStructure and VehicleJourneyStopAssignmentsInFrame_RelStructure - they
 The only difference is the lower/upper case of the first letter. Is this a mistake?

**Comment by skinkie** [comment]
I guess this is a mistake.

**Comment by Aurige** [comment]
the lowercase "v" version looks useless

**Comment by skinkie** [comment]
@Aurige it is actually the opposite.

**Comment by Aurige** [comment]
yes sorry .. I approved the corresponding PR

**Comment by skinkie** [comment]
@HPOkurDB thanks for reporting it. These kind of in depth reports help us to clean up the schema. I'll see if I can find a more automatic may to resolve used complex types.

**Comment by HPOkurDB** [comment]
@skinkie @Aurige thank you very much for your quick support.
