### ISSUE TITLE
Clear up the documentation regarding weekend and weekday.

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#514]
Since weekend depends on locale, document in the XSD what is intended here.

https://3.basecamp.com/3256016/buckets/2570434/messages/6603341976

**Comment by skinkie** [comment]
Within the group we discussed the following. It is very inconvenient to have a locate to determine what the meaning of the day type enumeration is. Our proposal would be to deprecate Weekdays and Weekend, but document what the current "western" of those are being Monday to Friday, and Saturday and Sunday. If the end user is interested in actually representing a clear cut between Weekdays and Weekend it could use a _Name_ or _Description_ on a parent element such as _AvailabilityCondition. 

```
        <xsd:simpleType name="DayOfWeekEnumeration">
                <xsd:annotation>
                        <xsd:documentation>Allowed values for Day of the Week.</xsd:documentation>
                </xsd:annotation>
                <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Monday"/>
                        <xsd:enumeration value="Tuesday"/>
                        <xsd:enumeration value="Wednesday"/>
                        <xsd:enumeration value="Thursday"/>
                        <xsd:enumeration value="Friday"/>
                        <xsd:enumeration value="Saturday"/>
                        <xsd:enumeration value="Sunday"/>
                        <xsd:enumeration value="Everyday"/>
                        <xsd:enumeration value="Weekdays"/>
                        <xsd:enumeration value="Weekend"/> 
                        <xsd:enumeration value="none"/>
                </xsd:restriction>
        </xsd:simpleType>
```

**Comment by ue71603** [comment]
addressed in https://github.com/NeTEx-CEN/NeTEx/pull/713

**Comment by Aurige** [comment]
Part 1 updated according to PR713
