### ISSUE TITLE
PassengerCapacity@id

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#515]
In relation to #471 I notice that the examples in prCEN-1 mention PassengerCapacity without an id attribute, while the table does suggest is is a required element.

![image](https://github.com/NeTEx-CEN/NeTEx/assets/502394/f03d4a67-fa17-4bdd-a585-833d591d1821)

![image](https://github.com/NeTEx-CEN/NeTEx/assets/502394/b0dca0bf-1a99-43d5-8dc3-c9b908b62443)

In your opinion what is wrong here?

**Comment by Aurige** [comment]
In this specific case, the _PassengerCapacity_ attribute has a type _PassengerCapacityStructure_ and does not ref the _PassengerCapacity_ element (this said, it can also be seen as an issue). So the example is Ok for now.

However, the element itself is defined as below, and the _<xsd:attribute name="id" type="PassengerCapacityIdType" use="**optional**">_ is not consistent with the documentation and should be fixed
```
<xsd:element name="PassengerCapacity">
		<xsd:annotation>
			<xsd:documentation>Capacity for a VEHICLE TYPE and Class.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base="PassengerCapacityStructure">
					<xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="EntityInVersionGroup" minOccurs="0"/>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="DataManagedObjectGroup"/>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="PassengerCapacityGroup"/>
						</xsd:sequence>
					</xsd:sequence>
					<xsd:attribute name="id" type="PassengerCapacityIdType" use="optional">
						<xsd:annotation>
							<xsd:documentation>Identifier of PASSENGER CAPACITY.</xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
```

**Comment by skinkie** [comment]
@Aurige in your opinion, similar to AccessibilityAssessment should have its own id+version attributes?

**Comment by Aurige** [comment]
That's the group discussion we had during meeting #13 around https://github.com/NeTEx-CEN/NeTEx/pull/471 that didn't find a conclusion yet

**Comment by skinkie** [comment]
@Aurige so either we fix the documentation xor the xsd? ;-)

**Comment by Aurige** [comment]
I guess we can fix the xsd here (set use="required")

**Comment by Aurige** [comment]
then we can remove the "need documentation" tag ;-)

**Comment by ue71603** [comment]
fixed by https://github.com/NeTEx-CEN/NeTEx/pull/579
