### ISSUE TITLE
Different platform-heights on same platform including sectors

### ISSUE THREAD

**Issue by DWillDB** [NeTEx-CEN/NeTEx#522]
Hello @skinkie , hello @ue71603 ,

We are reaching out to you in reference to the pull request https://github.com/NeTEx-CEN/NeTEx/pull/276.

We are currently facing the challenge of modeling platform heights. There are platforms that have varying heights along the track. This information is relevant for passengers with mobility restrictions to determine if, for example, they can board the train at the same height, such as with a wheelchair.

In NeTEx, quays (platforms) have only one property for a height. In addition to the varying platform heights, we also have sectors along the track (e.g., A, B, C, D, E, F, ...). These sectors are displayed for passengers on the information boards (e.g., 1st class on platform 1, sector B).  Our intention is to represent these sectors as boarding positions. We have now modeled platforms (QuayType: railIslandPlatform), platform-side areas next to the tracks (QuayType: railPlatform), and different heights (QuayType: railPlatformSector) as quays. Could you please confirm if we have correctly understood how to implement such a model within NeTEx EPIAP profile?

Thank you in advance for your support and time.

Best regards,
David

**Comment by skinkie** [comment]
@Aurige was there an alternative for Quay not to be a single point?

**Comment by ue71603** [comment]
@DWillDB A sector is also a Quay but on a lower "level".  A Quay can be a platform, a track, a group of sectors or a sector.  A BoardingPosition is a single door/gate. Usually that is not modeled currently.
You can use placeTypes in TypeOfPlaceRef to distinguish them. With SiteRef you can reference the parent (Quay or StopPlace).

**Comment by DWillDB** [comment]
@ue71603 , thank you. This is exactly what we need. We thought BoardingPosition could be also an area to board and not a single Point like a door or gate.
