### ISSUE TITLE
Prevent recursive object usages

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#526]
In the current model AlternativeText, may include AlternativeText as a child again. It has a recursive definition. I would like to propose to refactor the model never to allow this kind of things.

**Comment by Aurige** [comment]
I fully agree that we need to avoid and correct recursive definitions.
It looks that this one is already OK (the restriction from **_VersionedChildStructure_** explicitely exclude it), but if we find others we will have to solve them.
![image](https://github.com/NeTEx-CEN/NeTEx/assets/3328999/69d07866-5f64-4b32-a22b-88c98b5ab6e0)

**Comment by skinkie** [comment]
Thanks @Aurige that uncovered an interesting situation upstream.

**Comment by skinkie** [comment]
I have not found any recursion.
