### ISSUE TITLE
Missing LowerHandrailHeight in RampEquipment

### ISSUE THREAD

**Issue by DWillDB** [NeTEx-CEN/NeTEx#533]
Hello,
is there a reason why we can find the XSD-Element LowerHandrailHeight in the StairGroup but not in the RampEquipmentGroup? In our opinion we should also describe the height of the lower handrail in RampEquipment. What do you think?

Here the example of LowerHandrailHeight in the StairGroup.
https://github.com/NeTEx-CEN/NeTEx/blob/7a1af73cf6060c813c0be272fd77a2eaabf821d7/xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd#L382

Kind regards,
David

**Comment by skinkie** [comment]
I would agree, even the order of elements is not consistent with the rest.
