### ISSUE TITLE
What structure stores LinkSequenceProjection?

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#537]
Given that a ServiceJourney has the ability to provide a LinkSequenceProjection_Ref_, where can the _linkSequenceProjections_ be found as first order Frame member?

**Comment by Aurige** [comment]
it looks to be missing 
Also we never faced it most probably because the projection is really something you won't share with other object, and that's much better to have it embedded (as it is in all examples).
I would favour to deprecate the Ref from the _Rel structure

**Comment by skinkie** [comment]
That would mean, for example for a GTFS mapping, that each individual ServiceJourney would get its own LinkeSequenceProjection, which also does not make sense.

**Comment by ue71603** [comment]
A LinkProjection may be different from ServiceJourney to ServiceJourney. However, in frequency oriented traffic the LinkProjection will most often be the same for all ServiceJourney (e.g. cablecar).

**Comment by Aurige** [comment]
Ok, I had different use cases in mind ... so we need to add it

**Comment by nick-knowles** [comment]
If a LinkSequenceProjection is shared between journeys then it can be declared on the common JourneyPattern for the journeys.?  I dont think it needs to be declared at frame level.

**Comment by skinkie** [comment]
> If a LinkSequenceProjection is shared between journeys then it can be declared on the common JourneyPattern for the journeys.? I dont think it needs to be declared at frame level.

Then you can scrap all structures, because you can do it in a different way ;-) I would like to represent a GTFS feed, specifically shapes.txt how it has been described in GTFS. So a reference at trip level, to a single shape. Defining it once at a specific ServiceJourney and then referring from other ServiceJourneys to that one just does not make sense.

**Comment by ue71603** [comment]
addressed in https://github.com/NeTEx-CEN/NeTEx/pull/619 

Discussion continues there.
