### ISSUE TITLE
What is the difference between "NecessaryForceToOpen" and "OpeningNecessaryForce"?

### ISSUE THREAD

**Issue by DWillDB** [NeTEx-CEN/NeTEx#539]
Hello everyone,

We have identified two tags that appear to convey the same information, at least according to the documentation. Could you please clarify the difference between "NecessaryForceToOpen" and "OpeningNecessaryForce"?

You can access the XSD file by following this link.

https://github.com/NeTEx-CEN/NeTEx/blob/7a1af73cf6060c813c0be272fd77a2eaabf821d7/xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd#L1225

and

https://github.com/NeTEx-CEN/NeTEx/blob/7a1af73cf6060c813c0be272fd77a2eaabf821d7/xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd#L1240

Best regards,
David

**Comment by skinkie** [comment]
In the EPIAP documentation OpeningNecessaryForce is mentioned in a single example. NecessaryForceToOpen is mentioned a few times, and is earlier in the XSD too.

**Comment by ue71603** [comment]
...and we should take note for an editorial change in the specification
