### ISSUE TITLE
Gradient in TravelatorEquipment

### ISSUE THREAD

**Issue by hennadb** [NeTEx-CEN/NeTEx#553]
Hey all,

is it correct that the Gradient from the TravelatorEquipment is in Meters ? how can i understand it? Shouldnt it be degree?

https://github.com/NeTEx-CEN/NeTEx/blame/6d7067bc2cf4c7942c612b8ffe0d5ccf29d1f45b/xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd#L707-L710C22

**Comment by skinkie** [comment]
@hennadb I think you should read it as: you will have to walk a non-level surface for N meters.

**Comment by Aurige** [comment]
To me it is a bug ... all other gradients are in degree ... I'll make a PR

**Comment by duexw** [comment]
I think this is a bug in the comment. If you look at the xsd, the element above is "Length", and the comment has obviously just been copied from there.
![image](https://github.com/NeTEx-CEN/NeTEx/assets/28344454/641140ae-2c9b-4239-b9c2-51f47ad2b7f0)

**Comment by skinkie** [comment]
@duexw then it is also a bug in the type?

**Comment by duexw** [comment]
No, the type was decimal before the pull request, allowing for fractions of degrees (if anyone needs that).
