### ISSUE TITLE
Site Entrance qualifier 

### ISSUE THREAD

**Issue by Aurige** [NeTEx-CEN/NeTEx#556]
Shouldn't we have an qualifier on SiteEntrance to say that it is a main Entrance/Exit, secondary
 Entrance/Exit, service Entrance/Exit or Emergency Entrance/Exit ?
Probably to be added to SiteEntranceGroup
![image](https://github.com/NeTEx-CEN/NeTEx/assets/3328999/bb3010e0-cd1b-4453-bbf7-f3e0f63a4aee)

**Comment by skinkie** [comment]
I don't know how it is in France, but in The Netherlands I would consider even the back entrances of a stations to be 'very prominent'. Obviously there are less important entrances, but if you take a journey planner, wouldn't you want to enter the station were it is _close by_? Can you give a use case what this solves?

**Comment by Aurige** [comment]
For journey planning, when you don't know yet from where you will arrive, it's often that the main entrance is used as destination for a site (unless the journey planner supports multiple destination points, of course). Also when drawing a map, you usually have a bigger pitcogram for the main entrance. But I agree with you the closest is always the best.

**Comment by nick-knowles** [comment]
Relative importance /purpose of entrance could be added as a further EntrancePurpose enum .  Note that various other classifications  are already defined on SiteElementProperties, such as whether it is for public or private or staff us e only

Proposed revision

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/d138d996-36e7-4567-a393-17ca7c5032d5)

**Comment by Aurige** [comment]
just remove Staf value

**Comment by ue71603** [comment]
Through shop is secondary. Entrance has AvailabilityCondition. only enumeration. and attribute. 
@trurlurl will do a first draft

**Comment by ue71603** [comment]
@trurlurl  is there anything in this issue that is not in the PR? If not, I suggest to close the issue (not the PR).

**Comment by trurlurl** [comment]
> @trurlurl is there anything in this issue that is not in the PR? If not, I suggest to close the issue (not the PR).

Solved by #633, but not merged yet.

**Comment by trurlurl** [comment]
I see that we don't want to wait for the merge of the PR, so I close the issue.

**Comment by Aurige** [comment]
Part 1 updated (following https://github.com/NeTEx-CEN/NeTEx/pull/633)
