### ISSUE TITLE
TypeOfFuel for multiple fuel types

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#561]
A typical big boat has a CNG turbine engine and a Diesel engine. TypeOfFuel in VehicleType only allows a single value. There are now some values likes 'hybrid', I would say this should become an actual list.

**Comment by nick-knowles** [comment]
There is already a TypeOfPropulsion with values , combustion  electric, hybrid, electricAssist 
 (Shoudl perhaps also have  

So would just need to change Type of Fuel  to allow multiple fuel tyoes 

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/35dd7a4c-03c8-469a-91d7-baf637928f9d)

**Comment by ue71603** [comment]
fixed in https://github.com/NeTEx-CEN/NeTEx/pull/582
