### ISSUE TITLE
Align Capacities with SIRI and expand it e.g. for cars (in ferries)

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#565]
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/88d2e6c7-5ec4-4713-b0ae-379559111207)

**Comment by nick-knowles** [comment]
Both Transmodel and NeTEx  are open ended as to classifications s - model is mean to be generic and allow any type of classification 
![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/c1315c81-13e9-4b1d-a428-84ea862ca774)

If we anted to make mapping to SIRI easy we could add the SIri categories (WheelchaorPalce, PramPlace etc) as a fixed enums on DeckSpaceCapacity 

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/99fcaf94-3d75-45fb-a67e-4d39487883c1)

**Comment by ue71603** [comment]
From @nick-knowles  comment I removed the Transmodel label.

**Comment by ue71603** [comment]
addressed in#598

**Comment by Aurige** [comment]
Documentation updated for #598
