### ISSUE TITLE
Codespace/Description not a MultilingualString

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#567]

**Comment by nick-knowles** [comment]
I dont think this should be a mutlilanguage string - it is really metadata

**Comment by skinkie** [comment]
Then it should be a regular string in all other elements too?

**Comment by ue71603** [comment]
@Aurige @nick-knowles  @skinkie  if you can tell me what to do, I can do the PR.

**Comment by skinkie** [comment]
Check VehicleGroup too.

**Comment by Aurige** [comment]
All Description should be MutlilingualString, except if not shown top the public... PR to be drafted if it happens

**Comment by Aurige** [comment]
@skinkie update VehicleGroup
