### ISSUE TITLE
Consistency: why DeadRunJourneyPattern and not DeadRunPattern?

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#648]

**Comment by ue71603** [comment]
@Aurige  just tell us, if we should change this. Then a PR will be created.

**Comment by Aurige** [comment]
I can't find DeadRunPattern ! it is just referenced by constraine, but there is no element I can find

**Comment by Aurige** [comment]
![image](https://github.com/NeTEx-CEN/NeTEx/assets/3328999/3d220700-54b9-49f7-b891-267d59d1287e)

**Comment by Aurige** [comment]
just drop these constraints ?

**Comment by ue71603** [comment]
fixed with https://github.com/NeTEx-CEN/NeTEx/pull/655
