### ISSUE TITLE
Extend TypeOfFrame/ClassInFrameRef with ability to describe subelements that are minimally required

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#649]
In order to make a profile definition TypeOfFrame/ClassInFrameRef is an embedded way to describe a profile. What is currently lacking is the ability to describe the elements required in the profile.

If from this minimal definition a derived XML Schema (or Schematron) can be generated, every profile can be validated against an always up to date NeTEx upstream, without manual the manual labor of maintaining an extra XML Schema by hand (such as EPIP, Dutch, etc.)

**Comment by Aurige** [comment]
Datex 2 also worked in that direction, https://docs.datex2.eu/v3.0/profiling/index.html but in a different way (it looks to be a dedicated tool)

**Comment by ue71603** [comment]
you want a required="true" ?

**Comment by skinkie** [comment]
> you want a required="true" ?

Yes, but not on ClassInFrameRef, but on something like an Element under it. For example passingTimes are required er required in ServiceJourney for EPIP and Nordic profile. I would like to see something like:

```xml
<ClassInFrameRef ref="ServiceJourney">
  <ObjectInClassRef ref="Description" use="optional" /> <!-- minOccurs in root takes preference, hence this is redundant, but might be interesting to mention that the generic implementation would consider it -->
  <ObjectInClassRef ref="passingTimes" use="required" />
  <ObjectInClassRef ref="calls" use="prohibited" />
</ClassInFrameRef>
```

**Comment by ue71603** [comment]
fixed in https://github.com/NeTEx-CEN/NeTEx/pull/650
