### ISSUE TITLE
public_code in StopPlace

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#653]
ScheduledStopPoint in public_code is a PrivateCodeStructure, the same element in StopPlace is a str. We should aim for more consistency.

**Comment by ue71603** [comment]
@skinkie  in next?

**Comment by skinkie** [comment]
Yes. Do you remember what @nick-knowles mentioned regarding 'groups'? Shouldn't we aim for that?

**Comment by ue71603** [comment]
@skinkie  no recollection on my side.What should we aim for?

**Comment by skinkie** [comment]
If an element uses the same properties, make those properties generic as a group, and include the group.

**Comment by ue71603** [comment]
StopPointCodesGroup is a PublicCodeStructure same for StopPlace => close it.
