### ISSUE TITLE
`TactileActuators` attribute on Escalators and Travelators

### ISSUE THREAD

**Issue by juliustens-db** [NeTEx-CEN/NeTEx#665]
Hey everyone! Escalator and Travelator objects have an attribute called `TactileActuators`, with the description "wether [element] has a tactile actuator". People who build these equipments probably know exactly what that means, but as someone who is "just" implementing the standard, I struggle to understand the usage of this property. Could you provide some details on the usage of such an actuator in practice? (What does it control/activate?). Sorry if this is obvious and I'm just missing the point 😄

**Comment by ue71603** [comment]
@trurlurl  @Joostb61 Can we update the definition?

**Comment by Joostb61** [comment]
This is the description in the EPIAP functional document:
Whether there are buttons to start the escalator if it is not moving, and whether these buttons are intended and suited for the visually impaired.

**Comment by ue71603** [comment]
fixed in #720

**Comment by juliustens-db** [comment]
Thanks, that helps a lot! 🙂
