### ISSUE TITLE
Alignment of Bus_SimpleTimetable_Slovenia with the EU Profile

### ISSUE THREAD

**Issue by atibaut** [NeTEx-CEN/NeTEx#67]
Dear all,

I am in the process of aligning of my Slovenian timetable example
https://github.com/NeTEx-CEN/NeTEx/blob/master/examples/functions/timetable/Netex_09.2_Bus_SimpleTimetable_Slovenia.xml
to make it compatible with the NeTEx EU Profile (Passenger Information European Profile, prCEN TS 16614:PI Profile).
How am I supposed (and allowed) to do it...pull request through the issue, through my fork, directly through pull request, through my local branch? 

Kind regards,
Andrej

**Comment by skinkie** [comment]
Send a pull request to master.

**Comment by atibaut** [comment]
Stefan, thanks. 
I did it.
