### ISSUE TITLE
How to encode board-alight pair restrictions?

### ISSUE THREAD

**Issue by dvdkon** [NeTEx-CEN/NeTEx#691]
Hi all,
I'm working on creating a comprehensive dataset of Czech timetables and have run into a problem with existing open formats: Some bus lines in the Czech Republic don't allow passengers to travel within a city (for inter-city routes) or within the country (for international routes). There is no reasonable way to encode this in GTFS (an [extension](https://github.com/google/transit/issues/117) was proposed, but never merged), but I can't even find a way to do it in NeTEx.

In JDF (the dominant Czech standard), you can mark stops that a passenger can't travel between as belonging to a group. I couldn't find anything equivalent in NeTEx, so I hope there is some other way that I just didn't find.

A `ServiceJourney` can have exactly one `JourneyPattern`, so AFAIK I can't create multiple variants based on the boarding stop group without confusing consumers into thinking there's multiple buses running.

**Comment by skinkie** [comment]
@dvdkon thanks for the effort on doing this. There is a way do this in NeTEx, @Aurige answered this question before to me. Don't go forward with my GTFS trip duplication attempt, it is certainly an implementation option for journey planners, but for data exchange, it remains a hack.

Maybe @JohanEntur can maybe disclose how it was implemented in Norway.

@Aurige 's reply:

This really looks like being ROUTING CONTRAINTS ... we have plenty in France

We typically use it when a long-distance bus line is crossing a city and have several stop in that city: it is allowed to board or alight at any stop, but you can't board and alight in the same city.

In Transmodel and NeTEx, it is refined with Service Exclusion (typically to avoid competition between On demand and regular services) and transfer restrictions.

![image](https://github.com/NeTEx-CEN/NeTEx/assets/502394/375eb085-ee53-4d39-87c3-de41ace40a89)

**Comment by dvdkon** [comment]
Thanks a lot for your prompt reply, `RoutingConstraintZone` looks like just what I need.

A small additional question: It seems that this isn't part of EPIP. Is that right, or do I have an outdated/incomplete copy?

**Comment by skinkie** [comment]
@dvdkon EPIP is a simple variant. I wouldn't use it as reference or limitation. In my perspective the first step for a country would be to encode their national dataset in a national NeTEx profile that matches the concepts used as _closely_ as possible. EPIP is a derivative of that effort.
