### ISSUE TITLE
TrainElementType vs TrainElement

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#703]
for accessibility we need the concrete elements as well.

**Comment by nick-knowles** [comment]
Are there two separate questions here. How should we handle renaming of TrainElement to TrainElement type (Additional deprecated element?).  Do we nee to implemenet train composition elements as below so can distinguish between types and instances

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/e795c5b8-f8c9-4c4d-8438-ee79c8062e7c)

**Comment by ue71603** [comment]
Other problem: the new TrainElementType would contain the TrainElementGroup which contains an element TrainElementType which is an enumeration. Sorry, not thought trough.

**Comment by ue71603** [comment]
I think also, that was decided in Transmodel is in direct conflict with the new SIRI European profile. 
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/8cfbdfbd-c16a-4042-b740-02ac22681ddb)

I would like to see from you a picture of a Train with two TrainCompounds with 3 carriages each and then label, how this would need to be done with Type and concrete TrainElements (with EVN numbers).  Currently I think it is overengineered and the CompoundTrain TrainComponent etc is misleading at best.

And for demonstration the problem with TrainElementType within TrainElementType:
								<TrainComponent version="any" id="bbd:trncmp_40447_06" order="5">
									<Label>Carriage E</Label>
									<Description>5th Carriage</Description>
									<TrainElement version="any" id="bbd:trne_40447_06">
										<Name/>
										<TrainElementType>carriage</TrainElementType>
										<FareClasses>standardClass</FareClasses>
									</TrainElement>
								</TrainComponent>

If anything I would have prefered:

for type based data:
<TrainComponent ...
  <TrainElementType ....

for real vehicles
<TrainComponent ...
   <TrainElement .....

**Comment by ue71603** [comment]
Strangly enough TrainElementTypeGroup contains "equipments". Which can't be on a Type.

The renaming just doesn't work.

I guess we need really:

TrainElement (abstract)

TrainElementType inherits from TrainElement
ConcreteTrainElement inherits from TrainElement


We have TrainElementTypeGroup
  (which contains TrainElementTypeGroup and no equipments)
and we have ConcreteTrainElementGroup
  (which contains TrainElementTypeGroup and the equipments and the EVN number or at least a note, where to store it, if it exists)

Also: currently DECK PLAN only associates with the TrainElementType. I hope this is working for the use cases.

**Comment by Aurige** [comment]
It's a pretty long and complex discussion with a lot of inputs coming from rail people, and requires a synchronisation with TM, and SIRI ...
My main question is "can we stay with what we have ?" ... I'm not sure that we really have a instance related use case for NeTEx (probably more in the SIRI side).
If so, the fact that currently DECK PLAN only associates with the TrainElementTypeRef, need to be documented (or renamed to TrainElementRef) since our current TrainElementType is an enum (TrainElementTypeTypeEnumeration) which cannot be refered.

**Comment by ue71603** [comment]
What should the current situation be? TrainComposition is not implemented yet (and I oppose it).  Other stuff from DeckPlan is already integrated. And I think that TrainElement -> TrainElementType is in principle also be implemented already.

**Comment by Aurige** [comment]
The TRAIN COMPOSITION is "_A specific instance of a TRAIN composed of TRAIN COMPOSITION COMPONENTs in a certain order._", that's the " instance related use case" I'm mentioning. DeckPlan is Ok and independent (currently possibly assigned to VehicleType and specialisations, TrainComponent, TrainElement(Type) Journey or journeyPart). 
Isn't it enough for now ?

**Comment by ue71603** [comment]
My problem is, that this is exactly what TrainElement did (and does in Siri) before some people thought they needed a TrainElementType and then tried to rename TrainElement.  This results in Siri/OJP being no longer aligned with Transmodel.  I

**Comment by Aurige** [comment]
So you are against the renaming in Transmodel, right ?

**Comment by ue71603** [comment]
Oh, yes. it was a rash and not really thought out change like the whole DECK PLAN mess. I will move the discussion to basecamp.
