### ISSUE TITLE
RequestMethod

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#71]
A StopPointInJourneyPattern may have a RequestMethod. I would expect that there might be a variation between boarding and alighting. For example boarding via hand signal, and alighting via a stop button. In GTFS the boarding and alighting methods are separate. In addition I would expect that multiple request methods should be able to be used, similar to booking methods.

**Comment by Aurige** [comment]
That makes sense ! But it's difficult to change things now that the document has just be voted. May be that's something to be anticipated in the PSA for later CEN submission.

**Comment by skinkie** [comment]
The development of the XSD is separate from "the document".

**Comment by Aurige** [comment]
not 100%, they need to be synchronised at some point ... and everything in the doc has to be in the XSD

**Comment by nick-knowles** [comment]
We also need an additional enum value   for requestMethod of "AskDriver" (as in GTFS) 
I agree we need to add, but we should be clear how this revises the current semantccs
Would we in effect be saying that the current REuestMethod  is a "BoardingRequestMethod"
And what we need to add is   an "Alighting request method?"

**Comment by Aurige** [comment]
> Would we in effect be saying that the current REuestMethod is a "BoardingRequestMethod"
> And what we need to add is an "Alighting request method?"

yes, and most probably add possible multiplicity

**Comment by ue71603** [comment]
There seems to have been no progress there. @Aurige: In the new world: Would we do the pull request for doing this.
I guess: StopPointInPatternPropertiesGroup needs an element
BoardingRequestMethod  type BoardingRequestMethodTypeEnuemration
AlightingRequestMethod  type AlightingMethodTypeEnumeration.

@skinkie @Aurige  @nick-knowles : Would this do the job. The documentation will be aligned with the next NWI and we push the PR to next?

**Comment by Aurige** [comment]
Ok for me, but we need to keep the **RequestMethod** for compatibility reasons (maybe using a choice)

**Comment by ue71603** [comment]
and should we create additional ListOf?

**Comment by Aurige** [comment]
if we have use cases for it, yes

**Comment by ue71603** [comment]
I will make a suggestion with lists

**Comment by nick-knowles** [comment]
UML Updated. Spec still to do

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/bd1232b1-cb52-46e7-97cb-a5a9937094b1)

**Comment by ue71603** [comment]
I see
```
			<xsd:element name="BoardingRequestMethod" type="RequestMethodTypeListOfEnumerations" default="noneRequired" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Methods to Request Stop for boarding in this particular service pattern; Default is noneRequired.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="AlightingRequestMethod" type="RequestMethodTypeListOfEnumerations" default="noneRequired" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Methods to Request Stop for alighting in this particular service pattern; Default is noneRequired.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
```
So this part is no longer necessary (as it exists already)

askDriver from GTFS is speakToDriverOnBoard already implemented

So this issue is completly done.
