### ISSUE TITLE
GBFSMapping - mustPickUpandDRopOffToSameStop

### ISSUE THREAD

**Issue by nick-knowles** [NeTEx-CEN/NeTEx#716]
There are a number of minor  attributes in GBFS 3.0 that NeTEx does not support. Two relate to VEHICLE CONSTRAINT ZONE

1. GBFS  Geofencing_rule vehicle return constraints allow one to specify  that a vehicle must be returned to same stop ,that it was picked up from

NeTEx currently lacks this.  Suggest add new enum value to **ServiceZoneUseTypeEnum** of  _mustPickUpandDropOffToSameStop_

2. GBFS "Station_parking,allows one  to specify that in a specifi zone, vehicle must be collected  / returned from a station rather than anywhere in zone.   NeTEx current allows floating Vehicles for whole service but not for a specific zone.  

Suggest  add attribute  **_FloatingVehicles_** boolean to **VehicleTypeZoneRestriction**

Revised UML
![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/fcf818ea-3224-413e-8a60-b27fb9dc4e2e)

**Comment by ue71603** [comment]
addressed in https://github.com/NeTEx-CEN/NeTEx/pull/730
