### ISSUE TITLE
Reintroducing HoistOperatingRadius, if necessary.

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#718]
Member

![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/323ea6d5-a322-46cf-a7f4-136f72c5c526)

Author
@[skinkie](https://github.com/skinkie) skinkie 18 minutes ago
Where did this go?

Member
@[ue71603](https://github.com/ue71603) ue71603 3 minutes ago
to nowhere.. It is also not used.. and not in the spec document.. @trurlurl @Joostb61 @duexw . Problem that we need to include in 2.0?

@ue71603	Reply...

<xsd:element name="HoistOperatingRadius" type="LengthType" minOccurs="0">

				<xsd:annotation>
					<xsd:documentation>Distance from VEHICLE needed to operate hoist.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

**Comment by trurlurl** [comment]
I remember that this had been discussed for bus stops, to determine whether the width of the quay allows for operating the hoist.
