### ISSUE TITLE
NoticeAssignment for TimetabledPassingTime

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#734]
In NeTEx a Call can receive a NoticeAssignment. When transforming a Call structure to TimetabledPassingTimes it is not possible to copy the NoticeAssignment on that specific call to that specific passing time. A both the ServiceJourney and StopPointInJourneyPattern could receive a NoticeAssignment, but without further constraints not limited to that specific passing time.

A workaround (in EPIP) might be to assign a specific ServiceJourneyPattern having this notice. But this feels complex.

**Comment by ue71603** [comment]
@Aurige  Guidance needed.

**Comment by Aurige** [comment]
The NoticeAssignment is a first class object (can be included in serviceFrame, timetableFrame, fareFrame...) so any object with an Id can be assigned an Notice. This should work for TimetabledPassingTime.

**Comment by ue71603** [comment]
created PR, that deals with id. perhpas
