### ISSUE TITLE
I have a query (not an issue) about FrameDefaults 

### ISSUE THREAD

**Issue by AdeOpe** [NeTEx-CEN/NeTEx#74]
Hi @nick-knowles  & Team,
could you please provide some explanation regarding "FrameDefaults"

What are they are? and what do they mean?

I see some a comment saying
"The default means that actually we could leave off all ids that belong to the mb: namespace."

but could you please provide a bit more explanation as to what it means?

**Comment by Aurige** [comment]
Hello
FrameDefaults i a set of default values that applies to the all objects in theFrame: currency, type of units, location system, default responsibilities, etc. but also codespace: note here that it is codespace, for IDs, not XML namespaces

**Comment by AdeOpe** [comment]
ok thank you.
