### ISSUE TITLE
We are not checking for many examples (for example tap_tsi), and yes they break

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#740]

**Comment by ue71603** [comment]
What shall we do?  In theory the are and will be based on a given NeTEx version. They don't need and can't comply to NeTEx 2.0

**Comment by Aurige** [comment]
Do we have a list of the examples, especially to breaking ones (just to check why) ? ... I'm afraid we can't give a generic answer, it may be per case

**Comment by skinkie** [comment]
Just validate all examples, it is not that hard to find a file in the tap_tsi folder.

**Comment by ue71603** [comment]
I will go through them...

**Comment by Aurige** [comment]
Actions:
1. update the checking mechanism to catch all errors (but don't merge)
2. fix the examples and also add a deprecation to allow backward compatibility (to be done / PR per issue type)
