### ISSUE TITLE
DatedServiceJourney should get a DepartureDate

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#742]
I think DatedServiceJourney is missing a plain DepartureDate, it instead has an `OperatingDayRef` and `UicOperatingPeriod`, I think it should just have a plain XsDate as option.

**Comment by ue71603** [comment]
No, it must be an OperatingDay. That is very basic behaviour in DATED VEHICLE JOURNEY. Even when it causes some problem. It is perhaps a bad idea to call it OperatingDayRef, but it always are OPERATING DAYs.

**Comment by skinkie** [comment]
OperatingDayView is fine for me me too, but currently we only have an OperatingDayRef, hence a specific DatedServiceJourney cannot exists on its own, which is a problem.

**Comment by Aurige** [comment]
Can OperatingDayView can be a solution ?

**Comment by ue71603** [comment]
I analysed it some more.   The OperartingDayRef is considered mandatory for everything generated newly. I think we should change the cardinality now to that.  Also adding the OperatingDayView here, would be a strange use in  DatedVehicleJourneyReferencesGroup.  It did it, so we now might discuss (but I hate it that some unprepared stuff has to be done into a PR and the discussions start, that should have been done before.
