### ISSUE TITLE
HeadwayJourneyGroupGroup introduces a Description which is already present in GroupOfEntitiesGroup

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#748]
https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourneyFrequency_version.xsd#L294

https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_genericFramework/netex_grouping_version.xsd#L108

warning: Converting parent field `{http://www.netex.org.uk/netex}GroupOfEntities_VersionStructure::Description` to a list to match child class `{http://www.netex.org.uk/netex}HeadwayJourneyGroup`

Removing the extra Description in HeadwayJourneyGroupGroup resolves the issue.

In Next the same would go for PathLinkInSequenceGroup, removing the extra Description resolves the issue.

**Comment by ue71603** [comment]
@skinkie ok for me to remove it. Two PR? one to master and one to next?

**Comment by skinkie** [comment]
I have to check if the PathLinkInSequenceGroup is also in master.

**Comment by skinkie** [comment]
This is the same thing as #562

**Comment by ue71603** [comment]
@skinkie  PR to remove it?

**Comment by Aurige** [comment]
If that does not break examples (which is most most likely) I would remove this extra Description

**Comment by ue71603** [comment]
PR done

**Comment by skinkie** [comment]
@ue71603 will you do it for PathLinkInSequenceGroup as well?

**Comment by Aurige** [comment]
Doc updated via https://github.com/NeTEx-CEN/NeTEx/pull/783
