### ISSUE TITLE
Protect next

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#760]
https://github.com/NeTEx-CEN/NeTEx/commit/e30f7a9e93c6ed2a04595be9b6167b76eacf690f

@JohanEntur could commit, without even required to do a pull request...

**Comment by JohanEntur** [comment]
😏

**Comment by Aurige** [comment]
Github conf issue ?

**Comment by skinkie** [comment]
My hacker friend J0h4n3ntuЯ couldn't pass by the new next branch protections.
