### ISSUE TITLE
Optional order attributes

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#761]
Several types have optional order attributes. Such as AlternativeText, Assignment, JourneyPart, DeadRunCall, BlockPart, TrainComponent, CheckConstraint, CheckConstraintDelay, SeriesConstraint, FareElementInSequence, Leg.

In my opinion these should be consistent, and thus made required.

**Comment by ue71603** [comment]
@skinkie  close this as you now want them removed ?

**Comment by skinkie** [comment]
I think that is the only sound way to do it.
