### ISSUE TITLE
JourneyPart

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#78]
In the JourneyPart_VersionStructure type defined in the netex_coupledJourney_version.xsd file, the MainPartRef is JourneyPartCoupleRefStructure instead of JourneyPartRefStructure. In all examples of the standard, these references are filled with the JourneyPart reference, while the member description in the documentation contains the JourneyPartCouple reference (probably the documentation was generated from the annotation in xsd). The MainPartRef element is mandatory.

**Comment by Aurige** [comment]
Yes, you are right, that should be corrected, however, luckily,  that does not harm since both JourneyPartCoupleRefStructure  and JourneyPartRefStructure are in the VersionOfObjectRef substitution group

**Comment by janosu** [comment]
I checked the latest version the error still exists. The JourneyPart.MainPartRef type is JourneyPartCoupleRefStructure instead of JourneyPartRefStructure.

**Comment by nick-knowles** [comment]
I have submitted a fix for this
