### ISSUE TITLE
ServicePattern, ServiceJourneyPattern

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#79]
In the current model, ServicePattern can reference ServiceJourneyPatterns via the journeyPatterns element. Thus, this relationship is a one-to-many implementation. Wouldn't it be better to refer to ServicePattern with a reference in ServiceJourneyPattern, similar to TimingPattern? Thus, this relationship would be of the many-to-one type.

Note, this representation is problematic even if you want to process the NETEX file using SAX parsing, but I will write another issue about this.

**Comment by Aurige** [comment]
That's semantically equivalent... Also most often it is a 1-1 relation

**Comment by janosu** [comment]
Yes, you are partly right, but as far as I know ServiceJourneyPattern consists of ServicePattern and TimingPattern, where you can assign multiple TimingPatterns to a ServicePattern. This is significant if we assign different runtime or wait times to one or more TimingLink defined in TimingPattern. 

My problem is with model representation (the one-to-many relation), because in the current model ServicePattern points to one or more ServiceJourneyPatterns with one-to-many relations. It would be better for ServiceJourneyPattern to refer to ServicePattern and TimingPattern (it exists). Hierarchically, this is logical, not that ServicePattern refers in advance to ServiceJourneyPattern.

The problem still occurs when we want SAX parser processing on a NETEX file. For the current issue, when processing ServicePatterns, one-to-many relations would require solving references that will be processed later in the xml file.

**Comment by skinkie** [comment]
@janosu you suggest that to be able to use a SAX parser on a document is an objective. Parsing a document could work in multiple scans, of which one scan would account for creating an index to parsed objects, and only then the references are being resolved. I think we should open a separate issue for this, or discuss on BaseCamp (if you are not there, please let me invite you) what strategies are available for parsing and using NeTEx documents.

**Comment by ue71603** [comment]
@skinkie  Was this then discussed on Basecamp? Closeable here?

**Comment by urosjarc** [comment]
I would like to report probably related issue in this thread and reopen the issue, please close it if this linked issue is not relatable...
https://github.com/entur/netex-parser-java/issues/180

**Comment by urosjarc** [comment]
@ue71603 Could you provide more information about where this is beeing discussed I would love to read continuation of this issue.

**Comment by ue71603** [comment]
@aurige  Can you point @urosjarc  to the basecamp discussion?
