### ISSUE TITLE
Journey

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#80]
The TransportMode defined in Journey is currently of the AllVehicleModeOfTransportEnumeration type. This is not consistent with the TransportSubmode member because the list may contain a value that does not have TransportSubmode. There may be some type of anomaly here, or SelfDriveSubmode and TaxiSubmode may not be used as a TransportSubmode member.

In ValidityParameterAssignment, you can specify the vehicleMode and transportSubmode elements in the validityParameters member. These are in harmony with each other. It is noticeable that there are several modes of transport lists defined in NETEX (e.g.: AllVehicleModesOfTransportEnumeration, VehicleModeEnumeration, AllModesEnumeration etc.) , but as if they were used mixed in each entity and I do not understand why, so I think they may be due to a misspelling.

**Comment by Aurige** [comment]
Transmode Modes should be reworked soon due the request of the addition of New Modes (vehicle pooling, vehicle sharing, etc.) from the Commision. The design has already be done in Transmodel. This work will be the opportunity to clean this when needed.

**Comment by nick-knowles** [comment]
Agree  - historically journeys could only be on Public Transport.  This needs updating

**Comment by ue71603** [comment]
@Aurige  As new modes is now merged: Can you check what needs to be done?

**Comment by Aurige** [comment]
Yes, that's an action for the revision
