### ISSUE TITLE
SAX parsing

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#82]
When processing large xml files with a SAX parser, there is a problem with resolving some references to entities that have not been processed. In most cases, this would be possible if the members in the given version frame were in the correct order. For example, a ServiceFrame contains Route and Line entities, but the definition of Lines follows Routes while Route entities refer to Line. Similarly, in the same frame type, the Network entity can point to GroupOfLines entities. I think LineInFrameGroup should be ahead of NetworkInFrameGroup.
Of course, this does not solve circular references (see OppositeDirectionRef in Direction), but their number could be minimized by simple sequencing. If necessary, I can collect them.

**Comment by ue71603** [comment]
We will discuss in the wiki on how to parse NeTex files

**Comment by dekarl** [comment]
I have a similar use case. I'm importing large datasets (German DELFI dataset) using streaming. When handling a stop place hierarchy it would be helpful if a parentSiteRef only referenced sites that have already been handled.

Should a hierarchy of sites be serialized to XML in such a way that a streaming processor can handle the hierarchy? Can the processor rely on that order?

That would limit the valid order like this:
* General Stop Place
* * entrance
* * Quay
* * Monomodal Stop Place
* * * Quay
* * * Quay
* * Monomodal Stop Place
* * * Quay
* * * Quay

The example is modeled after chapter 6.1 in http://netex.uk/netex/doc/2019.05.07-v1.1_FinalDraft/prCEN_TS_16614-PI_Profile_FV_%28E%29-2019-Final-Draft-v3.pdf

An actual sample of the dataset is at https://github.com/opentripplanner/OpenTripPlanner/pull/5052#issuecomment-1509370605
