### ISSUE TITLE
 PublicCode type diversity

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#84]
In the current version, the PublicCode member in the entities is defined by several types. In most cases, it is a normal string field or a PublicCodeType which is derived from string, but there are entities with a PrivateCodeStructure type. Shouldn't it be uniform?

**Comment by skinkie** [comment]
I would agree on it.

**Comment by Aurige** [comment]
I agree too (no harm, but not clean...). PublicCode was not generalized initially, and there were several iterations before ending in the current status (not an excuse, just explaining).

**Comment by nick-knowles** [comment]
Yes - We should change them all to use the PublicCodeType

**Comment by ue71603** [comment]
@nick-knowles  @Aurige @skinkie  Should I create a PR now or do we wait to do this with the PrivateCode discussion in issue https://github.com/NeTEx-CEN/NeTEx/issues/32. For me it is ok to do it now

**Comment by Aurige** [comment]
Yes a PR would be nice, however, I'm not sure that there is an easy fix

**Comment by ue71603** [comment]
We have:
* PublicCodeType
* PrivateCodeStructure
* xsd:normalizeString
* ParkingPublicCodeType


- PublicCodeType is defined in netex_ifopt_stopPlace_support.xsd
- PrivateCodeStructure is in netex_utility_types as a xsd:normalizedString

**Comment by ue71603** [comment]
I close this one. the PR includes everything.
