### ISSUE TITLE
LinkProjection

### ISSUE THREAD

**Issue by janosu** [NeTEx-CEN/NeTEx#92]
The LinkProjection element in the netex_framework/netex_genericFramework/netex_projection_version.xsd file, is missing the EntityInVersionGroup. All of other Projection based class contains it, and the base DataManagedObject class is contains too. I think it was left out of the derivation.

**Comment by nick-knowles** [comment]
Yes you are right -   we simply need to expose the elements . I have made a  suggested  fix.

**Comment by janosu** [comment]
I closed the issue, without wait for a commit.

**Comment by janosu** [comment]
I was wrong.
